### ISSUE TITLE
FallbackComponent not rendering

### ISSUE THREAD

**Issue by DimoDimchev** [bvaughn/react-error-boundary#102]
Relevant code: 
```js
function ErrorFallback({ error }) {
		return (
			<div role="alert">
				<p>Something went wrong:</p>
				<pre style={{ color: "red" }}>{error.message}</pre>
			</div>
		);
	}

	return (
			<ErrorBoundary
				FallbackComponent={ErrorFallback}
				onReset={() => window.sessionStorage.clear()}
				onError={(error) => {
					console.log(error);
				}}
			>
                            <button onClick={( ) => {throw new Error("Testing with an error")}}>Error thrower</button>
                       </ErrorBoundary>
```

When I click on the button that triggers an error the FallbackComponent doesn't render, even though the error gets logged(onError recognises it). Am I missing something?

**Comment by JonhnyDev** [comment]
Here neither working, neither onError nor FallbackComponent

`import '../styles/globals.css'
import '../styles/FullCalendar/common/main.css'
import '../styles/FullCalendar/daygrid/main.css'
import React from 'react';
import { Provider } from "react-redux"
import { PersistGate } from 'redux-persist/integration/react'
import { createWrapper } from "next-redux-wrapper"
import { store, persistor } from "../store"
import { SnackbarProvider , useSnackbar } from 'notistack';
import CancelIcon from '@material-ui/icons/Cancel';
import ProviderAuth from 'next-auth/client'
import { ErrorBoundary } from "react-error-boundary";

function MyApp({ Component, pageProps}) {
  const DismissAction = ({ id }) => {
    const { closeSnackbar } = useSnackbar()
    return (<CancelIcon style={{cursor: 'pointer', marginLeft: -10}} onClick={() => closeSnackbar(id)}>Close</CancelIcon>)
  }
  React.useEffect(() => {
    // Remove the server-side injected CSS.
    const jssStyles = document.querySelector('#jss-server-side');
    if (jssStyles) {
      jssStyles.parentElement.removeChild(jssStyles);
    }
  }, []);
  const ErrorFallback = ({error}) => {
    console.log('error', error.message)
      return (
          <div role="alert" style={{width: '100%',height: '100%',zIndex: 9999, backgroundColor: 'white', display: 'flex'}}>
            <p>Ops.. ocorreu um erro</p>
            <pre style={{ color: "red" }}>{error.message}</pre>
          </div>
      );
  }
  return(
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <SnackbarProvider preventDuplicate maxSnack={3} action={key => <DismissAction id={key} />}>
              <ProviderAuth.Provider session={pageProps.session} >
              <ErrorBoundary FallbackComponent={ErrorFallback} onError={(error) => {
                console.log(error);
              }}>
                <Component {...pageProps} />
                </ErrorBoundary>
              </ProviderAuth.Provider>
            </SnackbarProvider>
          </PersistGate>
        </Provider>
  );
}

const makeStore = () => store;

const wrapper = createWrapper(makeStore, {debug: true}) 
export default wrapper.withRedux(MyApp);
`

**Comment by raDiesle** [comment]
In my understanding, the Fallback component is only rendered in production mode, not development. Is this correct?
If yes, it would be nice to temporary overcome this for testing purposes or/and document it more visible

**Comment by jdcoder27** [comment]
error boundary doesn't catch error in event handler, if you want catch error in event handler try to use useErrorHandler hook.
https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries

**Comment by chriszrc** [comment]
@raDiesle fallback works just fine in development mode. @JaedeokK is right. In my case, I was `catch`-ing errors from fetch, so they never bubbled up-

**Comment by GideonMax** [comment]
@JonhnyDev Can you provide the code for the child component that's throwing the error that doesn't get caught by the error boundary?

**Comment by bvaughn** [comment]
This answer is correct: https://github.com/bvaughn/react-error-boundary/issues/102#issuecomment-1014850123
