### ISSUE TITLE
React Router stopped working after Error Boundary and history.push doesn't work. How can it be fixed?

### ISSUE THREAD

**Issue by evgeny-s** [bvaughn/react-error-boundary#103]
- `react-error-boundary` version: 3.1.3
- `node` version: 14.17.1
- `npm` version: 6.14.13

Relevant code or config

```js
<Router>
  <ErrorBoundary>
    ...
  </ErrorBoundary>
</Router>

history.push('...') - doesn't work in the FallbackComponent
```

What you did:
Added new Exception to test Error Boundary
What happened:
App crashed, I can see my FallbackComponent

Reproduction repository:

Problem description:
history.push doesn't work from within ErrorBoundary component
Suggested solution:

**Comment by LongLiveCHIEF** [comment]
What version of react-router are you using?

**Comment by bvaughn** [comment]
Closing since no repro was provided. Hope you got it sorted out though!
