### ISSUE TITLE
How can i use componentStack in FallbackComponent?

### ISSUE THREAD

**Issue by akinsibay** [bvaughn/react-error-boundary#105]
Problem description:
I need to use componentStack in FallbackComponent but i see that the FallbackComponent only takes error and resetErrorBoundary parameters. That's why I can't access the componentStack information. How can I do it?

**Comment by aerlaut** [comment]
Unfortunately, the current implementation does not store `errorInfo` into the state, so it can not be accessed by the renders.

**Comment by bvaughn** [comment]
The short answer is: You can't.

This was by design, in React itself, which doesn't expose component info to `getDerivedStateFromProps` but only to `componentDidCatch`. I'm going to follow React's lead on this, rather than add a re-render.
