### ISSUE TITLE
Allow rendering of children components

### ISSUE THREAD

**Issue by aerlaut** [bvaughn/react-error-boundary#106]
- `react-error-boundary` version: 3.1.4
- `node` version: 14.18.1
- `npm` version: 6.14.15

Relevant code or config

```js
      const props = {
        error,
        resetErrorBoundary: this.resetErrorBoundary,
      }
```

Problem description:

I want to continue showing the children components after the error has been caught, so ErrorBoundary acts like a transparent container.

Suggested solution:

Allow rendering of child components inside fallback components by passing `children` in `props` on line https://github.com/bvaughn/react-error-boundary/blob/master/src/index.tsx#L121-L124.

**Comment by srsajjad** [comment]
This would be helpful to show some kind of modal / popup

**Comment by zbyte64** [comment]
I'm afraid that alone wouldn't be enough. You can't show the child components because their new state can't be rendered, you would need to pass in child components from a time prior to the error.

**Comment by NotoriousPyro** [comment]
If the error is being caused by the child component you're trying to render, and you try to render it even though it errored, you'll end up in an infinite loop. I know because I tried it, it caused a loop, and realised what I was doing was not going to work well.
