### ISSUE TITLE
UMD version can be inadvertently tree-shaken out because `sideEffects` is set to false

### ISSUE THREAD

**Issue by hongrich** [bvaughn/react-error-boundary#108]
**What you did:**

Attempt to bundle react-error-boundary using Rollup.js with `nodeResolve({browser: true})`.

**What happened:**

The UMD version of react-error-boundary is used and its content are completely gone in the bundled version.

**Reproduction repository:**

https://replit.com/@hongrich/react-error-boundary

**Problem description:**

react-error-boundary includes a UMD version as the `browser` entry point in package.json and it also specifies `"sideEffects": false`. These two options configured in this way are not compatible.

This reproduction shows the problem this can cause by bundling using Rollup.js. Using the node-resolve and commonjs plugin, we also set `browser: true` so it'd pick the browser entry point from package.json which is the UMD version.

Press the "run" button to run Rollup.
Note that `react-error-boundary.umd-<hash>.js` exports just `{exports: {}}`
and this is used in `b-<hash>.js` as part of the `Bar` function.

```js
//→ react-error-boundary.umd-b07bb2f5.js:
var reactErrorBoundary_umd = {exports: {}};

export { reactErrorBoundary_umd as r };

//→ b-8274de67.js:
import { r as reactErrorBoundary_umd } from './react-error-boundary.umd-b07bb2f5.js';

const Bar = () => {
  return reactErrorBoundary_umd.exports.ErrorBoundary
};

export { Bar };
```

**Suggested solution:**

Either removing `"sideEffects": false` from package.json or changing the `browser` field so that it doesn't export the UMD version are both reasonable solutions.

For reference, here are some other libraries built with `kcd-scripts` and none of them have this particular combination of fields (most just export CJS in `main` and ESM in `module`): https://sourcegraph.com/search?q=context:global+kcd-scripts+build+--bundle+repo:npm/&patternType=literal

**Comment by bvaughn** [comment]
Dropping UMD support in v4.0.0 (#131) so I'm going to close this.
