### ISSUE TITLE
'ErrorBoundary' cannot be used as a JSX component

### ISSUE THREAD

**Issue by rafalradomski** [bvaughn/react-error-boundary#111]
Hi guys, I get a strange typescript error when I use the default first example from your lib:

**'ErrorBoundary' cannot be used as a JSX component**, any chance you had seen that before?

<img width="647" alt="Screenshot 2022-04-15 at 15 41 08" src="https://user-images.githubusercontent.com/8066536/163584676-5d70f0ad-7385-416a-8cbe-043af6aead7c.png">

- `react-error-boundary` version: 3.1.4
- `node` version: 14.19.0
- `npm` version: 6.14.16

`
import {ErrorBoundary} from 'react-error-boundary'
function ErrorFallback({error, resetErrorBoundary}) {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
      <pre>{error.message}</pre>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  )
}
const ui = (
  <ErrorBoundary
    FallbackComponent={ErrorFallback}
    onReset={() => {
      // reset the state of your app so the error doesn't happen again
    }}
  >
    <ComponentThatMayError />
  </ErrorBoundary>
)
`

**Comment by kaspnilsson** [comment]
Also getting this in my project, it appears to have something to do with the version of react I have in my project being different than what's expected.

Key code lines:

```tsx
import { ReactNode } from 'react'
import { ErrorBoundary as ReactErrorBoundary } from 'react-error-boundary'

interface Props {
  children: ReactNode
}

const ErrorBoundary = ({ children }: Props) => {
// my custom wrapping code
  return (
    <ReactErrorBoundary FallbackComponent={ErrorFallback} onError={onError}>
      {children}
    </ReactErrorBoundary>
  )
}
```

Error:
'ReactErrorBoundary' cannot be used as a JSX component.
  Its instance type 'ErrorBoundary' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("node_modules/@types/hoist-non-react-statics/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.

The particular node module it conflicts with changes each time I do a fresh `yarn install`, so it seems to be an issue with this lib as opposed to other deps.

**Comment by cmdcolin** [comment]
probably related to changes in @types/react v18

**Comment by cmdcolin** [comment]
I added
```
  "resolutions": {
    "@types/react": "^17.0.0"
  }
```

to my package.json to pin to @types/react v17 for now

**Comment by mantey-github** [comment]
Also facing this same issue

**Comment by edouardmisset** [comment]
I also have the same issue.

```
'ErrorBoundary' cannot be used as a JSX component.
  Its instance type 'ErrorBoundary' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/home/ext_em/code/innova-web-ui-proto/node_modules/@types/react-redux/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.
```

package.json
```json
  "dependencies": {
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-error-boundary": "^3.1.4",
    ...
}
```

**Comment by andreribeiro27** [comment]
Same issue

**Comment by fabioebt** [comment]
Same here

**Comment by AndyJPG** [comment]
Having the same issue as well

**Comment by Hendry5479** [comment]
Need to upgrade the version of  @types/react

**Comment by tomtang1122** [comment]
I also have the same issue.

**Comment by nardocesar** [comment]
Same here

**Comment by sam-frampton** [comment]
same here

**Comment by bnheise** [comment]
Same issue

**Comment by zlargon** [comment]
This issue is caused by the breaking change from [@types/react](https://www.npmjs.com/package/@types/react) v18.

Use command `npm ls @types/react` to see if you have any `@types/react@18.x` in your dependencies.

You can upgrade react v18, or update `@types/react@17.x` version in your lock file.

Checkout the solution from these comments:
- https://github.com/facebook/react/issues/24304#issuecomment-1094565891
- https://github.com/facebook/react/issues/24304#issuecomment-1092563688

**Comment by blockmood** [comment]
Same here

**Comment by floatrx** [comment]
👋 **Very simple solution:**  this `return this.props.children` replace with `return <>{this.props.children}</>`

**Comment by lucksp** [comment]
> upgraded my App's `@types/react` which solved issue.

Nevermind...the `tsc` type check still fails.

**Comment by Gyumong** [comment]
Same here

**Comment by mtwichan** [comment]
Same here

**Comment by mayassalman** [comment]
Same here

**Comment by bvaughn** [comment]
Assuming [this](https://github.com/bvaughn/react-error-boundary/issues/111#issuecomment-1262939766) is the solution, this issue should no longer be relevant with v4 since `ErrorBoundary` will wrap `children` within a `<Context.Provider>`. Let's re-open with a repro case if the issue still happens in v4.
