### ISSUE TITLE
Error + Children

### ISSUE THREAD

**Issue by piotrpodyma10** [bvaughn/react-error-boundary#112]
Hi,

I checked your package and I see that I can display children or error. Is it possible to display Children + Error at the same time (for example Modal)? 

Best

**Comment by bvaughn** [comment]
Not with this component. Children are rendered by default. If children throw an error, this component catches it and renders some sort of fallback as determined by its props:
https://github.com/bvaughn/react-error-boundary/blob/a0a370c7fe145e5cf169063eb4b7ff1a059fd84c/src/index.tsx#L115-L140

I don't think it makes sense to re-render children if they have already thrown. (They would likely just throw again, defeating the purpose of an error boundary). But if you think there is a use case where this makes sense, you can definitely build it yourself using React's error boundaries API: https://reactjs.org/docs/error-boundaries.html
