### ISSUE TITLE
'ErrorBoundary' cannot be used as a JSX component error with vite.js builder

### ISSUE THREAD

**Issue by othierry-asi** [bvaughn/react-error-boundary#113]
I have a problem with `react-error-boundary` error when migrating from CRA to vite.js (2.9.12).

- `react-error-boundary` version: 3.1.4
- `node` version: 14.9.3
- `npm` version: 6.14.7

I use ErrorBoundary this way in my app :

```js
const App = () => {
  return (
    <ThemeProvider>
      <ErrorBoundary FallbackComponent={ErrorFallback} onError={errorHandler}>
        <BrowserRouter basename="/xxxx/">
          <Layout toggleTheme>
            <div className={"max-w-7xl w-full m-auto px-3 py-5"}>
              <RouterConfig />
            </div>
          </Layout>
        </BrowserRouter>
      </ErrorBoundary>
    </ThemeProvider>
  );
};
```

When I run `yarn run build` I have the following error :

```
src/app/App.tsx:18:8 - error TS2786: 'ErrorBoundary' cannot be used as a JSX component.
  Its instance type 'ErrorBoundary' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'React.ReactNode' is not assignable to type 'import("/xxx/node_modules/@types/react-redux/node_modules/@types/react/index").ReactNode'.
        Type '{}' is not assignable to type 'ReactNode'.

18       <ErrorBoundary FallbackComponent={ErrorFallback} onError={errorHandler}>
```

It used to work very well with CRA.

Any idea what happens ?

**Comment by gtroupisiag** [comment]
https://github.com/bvaughn/react-error-boundary/issues/111#issuecomment-1125544782
This other issue that is open says to upgrade `@react/types` to version 18

**Comment by othierry-asi** [comment]
Oh sorry, I can't understand how I could not see it ! I close this one.

**Comment by floatrx** [comment]
👋 **Very simple solution:**  this `return this.props.children` replace with `return <>{this.props.children}</>`

**Comment by Ludovicmanga** [comment]
Thanks @floatrx, works for me now

**Comment by teddybee** [comment]
I have the same issue with NextJs 13.4. 
Typedefs and children are checked.

**Comment by bvaughn** [comment]
The return types for class components and function components are kind of silly. If React can render a `ReactNode`, why isn't that a valid return type 😕

**Comment by teddybee** [comment]
Tank you this helped:
```
 "resolutions": {
    "@types/react": "^18.2.7",
}
```
But I still don`t know why this roundabout is necessary.
