### ISSUE TITLE
browser field for package.json serv umd to webpack instead of module esm

### ISSUE THREAD

**Issue by kopax-polyconseil** [bvaughn/react-error-boundary#114]
- `react-error-boundary` version: 3.1.4
- `node` version: 16
- `yarn` version: 3.1.4

## What you did:

I did build my web application

## What happened:

![image](https://user-images.githubusercontent.com/77674046/183102056-638cc221-cdbb-415e-9683-24e156365e7a.png)

umd was bundled

I have tried to edit your `package.json` in our `node_modules` using `patch-package`:

```
$ npx patch-package react-error-boundary
patch-package 6.4.7
• Creating temporary folder
• Installing react-error-boundary@3.1.4 with yarn
• Diffing your files with clean files
⁉️  Not creating patch file for package 'react-error-boundary'
⁉️  There don't appear to be any changes.
dka@dka:[~/workspace/github.com/pass-culture/pass-cul
```

It didn't work so I fixed it with a `resolve.alias`:

```
  966.23 KB (-116 B)  build/static/js/2.b64446a8.chunk.js
  556.98 KB (-4 B)    build/static/js/main.b139b737.chunk.js
```

This saves use 118B :)

## Reproduction repository:

Not necesssary

## Problem description:

umd is the heaviest format, because it support all kind of import, while we need a light format for our ES webapp. 

According to https://github.com/webpack/webpack/issues/4674, browser is prioritary in webpack than module field

Suggested solution:

See https://github.com/webpack/webpack/issues/4674

**Comment by bvaughn** [comment]
UMD support will be dropped in v4 (#131) and the `package.json` will be changed significantly.
