### ISSUE TITLE
Bug: truthy check in useErrorHandler

### ISSUE THREAD

**Issue by sumedhdev** [bvaughn/react-error-boundary#115]
- `react-error-boundary` version: 3.1.4
- `node` version: 16.16.0
- `npm` version: 8.11.0

Relevant code or config

```js
const {data, error, loading} = useMyDataFetchingHook();
// if error = false ...
useErrorHandler(error);
// ...will still treat it as an error! 
// This contradicts the line in the readme that states "if the error is ever set to a truthy value, then it will be propagated to the nearest error boundary." i.e. the primitive false in JavaScript is (obviously) not truthy.
```

What you did:
(see above)

What happened:
(see above)

Problem description: check in useErrorHandler contradicts the line in the readme that states "if the error is ever set to a **truthy** value, then it will be propagated to the nearest error boundary."

Suggested solution:

Bug is on this line:  
https://github.com/bvaughn/react-error-boundary/blob/master/src/index.tsx#L163
`if (givenError != null) throw givenError` 
should be 
`if (givenError) throw givenError`

Not directly related but the next line 
`if (error != null) throw error`
should also be 
`if (error) throw error`

**Comment by bvaughn** [comment]
Fixed in version 4 (#131) which changes the API.
