### ISSUE TITLE
Fallback component not shown

### ISSUE THREAD

**Issue by arturohernandez10** [bvaughn/react-error-boundary#116]
- `react-error-boundary` version: 3.1.4
- `node` version: stackblitz
- `npm` version: stackblitz

Relevant code or config

```js
import React, { Component, useState, useEffect } from 'react';
import { render } from 'react-dom';
import { ErrorBoundary } from 'react-error-boundary';
import './style.css';

const Profile = (props) => <div>Name: {props.user.name}</div>;

function Bomb() {
  useEffect(() => {
    throw new Error('💥 KABOOM 💥');
  }, []);
  return <p>Bomb</p>;
}

function ErrorFallback({ error, componentStack, resetErrorBoundary }) {
  return (
    <div role="alert">
      <p>Something wesssnt wrong:</p>
      <pre>{error.message}</pre>
      <pre>{componentStack}</pre>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  );
}

function App() {
  const [explode, setExplode] = useState(false);
  return (
    <div>
      <button onClick={() => setExplode((e) => !e)}>toggle explode</button>
      <ErrorBoundary
        FallbackComponent={ErrorFallback}
        onReset={() => setExplode(false)}
        onError={console.error}
      >
        {explode ? <Bomb /> : null}
      </ErrorBoundary>
    </div>
  );
}

render(<App />, document.getElementById('root'));

```

Problem description:

The error boundary does not show up here is a [stackblitz](https://stackblitz.com/edit/react-16-error-boundary-wrapper-6gwzq3?file=index.js,package.json) link

**Comment by austingayler** [comment]
I'm not sure if something changed, but react error boundaries don't work for event handlers: https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries . So this library still works, but the documentation shows an example that isn't supported by the underlying API...

To confirm:
```
const ErrorComponent = () => {
  throw Error("heck");
  return <p>should never render this</p>;
}
...
return <ErrorBoundary><ErrorComponent /></ErrorBoundary>
```

**Comment by arturohernandez10** [comment]
Just to verify if this could be a React issue, I used the modified the codepen in their documentation replacing `BuggyCounter` with the code below. And in this case the boundary does work as expected.

```
function Bomb() {
  React.useEffect(() => {
    throw new Error('💥 KABOOM 💥');
  }, []);
  return <p>Bomb</p>;
}

class BuggyCounter extends React.Component {
  constructor(props) {
    super(props);
    this.state = { counter: 0 };
    this.handleClick = this.handleClick.bind(this);
  }
  
  handleClick() {
    this.setState(({counter}) => ({
      counter: counter + 1
    }));
  }
  
  render() {
    if (this.state.counter === 5) {
      // Simulate a JS error
      throw new Error('I crashed!');
    }
    return <><h1 onClick={this.handleClick}>{this.state.counter}</h1>
      {this.state.counter ===3 ? <Bomb /> : <></>}
    </>;
  }
}
```

Since the codepen cannot be easily forked.

**Comment by dhatGuy** [comment]
I don't know if this has something to do with React 18. Rendering the root component with `ReactDOM.render(<App />, document.getElementById('root'))`, fallback component is shown.

**Comment by bvaughn** [comment]
> I'm not sure if something changed, but react error boundaries don't work for event handlers

That's correct. See this bit in the [React docs](https://legacy.reactjs.org/docs/error-boundaries.html):
> Error boundaries catch errors during rendering, in lifecycle methods, and in constructors of the whole tree below them.

An error thrown from an effect (as shown in this issue) should be caught, but an error thrown from an async callback in an effect would not be caught or handled by React.

As for the issue being reported here, it seems to work okay when I run it on Code Sandbox:
https://codesandbox.io/s/compassionate-black-xykuxj?file=/src/App.js
