### ISSUE TITLE
ErrorHandler from useErrorHandler() triggers crash when called in component rendering ErrorBoundary 

### ISSUE THREAD

**Issue by obasille** [bvaughn/react-error-boundary#117]
- `react-error-boundary` version: 3.1.4

Relevant code or config

```js
import React from 'react';
import { ErrorBoundary, useErrorHandler } from 'react-error-boundary';

function ErrorFallback({ error, resetErrorBoundary }) {
  return (
    <div>
      <h1>{error.message}</h1>
      <button onClick={resetErrorBoundary}>
        Clear
      </button>
    </div>
  );
}

function SomeComponent() {
  const handleError = useErrorHandler();
  return (
    <button onClick={() => handleError(new Error('Error from child'))}>
      Error from child
    </button>
  );
}

export function App(props) {
  const handleError = useErrorHandler();
  return (
    <div>
      <ErrorBoundary FallbackComponent={ErrorFallback}>
        <SomeComponent />
        <button onClick={() => handleError(new Error('Error from parent'))}>
          Error from parent
        </button>
      </ErrorBoundary>
    </div>
  );
}
```

What you did:
Calling `handleError()` from the same component that is rendering `ErrorBoundary`.
1. Calling `handleError()` from `SomeComponent` works
2. Calling `handleError()` from `App` triggers a crash

What happened:
The call seems to throw an exception that is not caught by ErrorBoundary and the app crashes.

**Comment by ChamsBouzaiene** [comment]
this happened because in the second case you are throwing the error outside of the error boundary, the error is originating in this hook `  const handleError = useErrorHandler();`  which is not a child of the boundary so it doesn't get caught

**Comment by obasille** [comment]
A workaround would be to store the error in a react state and be able to pass it to the `ErrorBoundary` component.

**Comment by bvaughn** [comment]
Closing this issue since the hook mentioned is being replaced by a new `useErrorBoundary` hook in version 4 (see #131)
