### ISSUE TITLE
onError callback called multiple times

### ISSUE THREAD

**Issue by azadorolabs** [bvaughn/react-error-boundary#119]
- `react-error-boundary` version: 3.1.4
- `node` version: v16.13.2
- `npm` version: 8.1.2
- `react` version: 17.0.2

Relevant code or config

 ```
function ErrorFallbackComponent ({ error }: any) {
    return (
      <div role="alert">
        <p>Something went wrong:</p>
        <pre>{error.name} : {error.message}</pre>
      </div>
    )
  }

  const errorHandler = (error: Error, info: {componentStack: string}) => {
    // log to an error to logging server - this is called multiple times
    const logError = error && error.name ? JSError[error.name] : JSError.InternalError
    loggingError(logError)
      .then(resp => console.log('error log to server'))
  }

<ApolloProvider client={ApolloGraphQLService.getInstance().client}>
      <ErrorBoundary FallbackComponent={ErrorFallbackComponent} onError={errorHandler}>
        <BrowserRouter>
          <div className="App">
            <div className="App-routes">
              <Routes></Routes>
            </div>
          </div>
        </BrowserRouter>
      </ErrorBoundary>
    </ApolloProvider>

```
What you did:
Logging error to server using onError callback

What happened: 
I am trying to send error caught by ErrorBoundry to server but onError callback called multiple times due to this multiple api calls in network.

**Comment by azadorolabs** [comment]
@bvaughn could you please take look into this and let me know if i missed something hear

**Comment by aquibbaig** [comment]
can you try wrapping `errorHandler` in a useCallback to make React use the same function instance across re-renders?

Else you can actually debug this by checking if your component is actually rendering multiple times:
```
<ErrorBoundary FallbackComponent={ErrorFallbackComponent}  onError={(e) => console.log("called")}>
...
</ErrorBoundary>
```

**Comment by bvaughn** [comment]
The `onError` prop is called from within `componentDidCatch` – which should only be run once per render+error thrown. (This is something React itself manages, not this library.) If your callback is called multiple times– I think that means multiple unique errors are being thrown (or there is more than one boundary).

Without a repro case, I can't be certain though.
