### ISSUE TITLE
Is this repository no longer maintained?

### ISSUE THREAD

**Issue by stimw** [bvaughn/react-error-boundary#121]
Or just no need to update anything?

**Comment by npearson72** [comment]
@flying-sheep what makes you think that's a valuable improvement?

**Comment by flying-sheep** [comment]
- `FallbackComponent` doesn’t have access to the context in which `ErrorBoundary` is used
- `fallback` neither

The way to solve this would be an awkward memoized inline component:

```js
const MyComp = ({ thing }) => {
  const Fallback = useCallback(({ error, resetErrorBoundary }) => (
    <something thing={thing} error={error} reset={resetErrorBoundary} />
  ), [thing])

  return <ErrorBoundary FallbackComponent={Fallback}>...</ErrorBoundary>
}
```

The API proposed in #120 is much nicer as you don’t have to manually pass things down awkwardly.

**Comment by npearson72** [comment]
Can't you just use the error prop in the fallback component?

**Comment by flying-sheep** [comment]
That’s what my solution does. However, to also use context (in my example a variable called `thing`), you need to define an inline component, which isn’t a an elegant thing to do. Therefore, #120 would be a good addition.

**Comment by bvaughn** [comment]
> Is this repository no longer maintained?

Not actively, no. I didn't have big ambitions for this project– and it already does a lot more than the basics I had in mind. :smile: Open source projects will take all the time and energy you give them and they don't give a lot back, so I don't check these issues often.

PR #120 does look pretty nice.
