### ISSUE TITLE
useErrorHandler rethrows errors, leading to uncaught errors in console

### ISSUE THREAD

**Issue by viveleroi** [bvaughn/react-error-boundary#126]
I'm using `useErrorHandler` to catch errors from an `axios` request. Its *working* in that the parent ErrorBoundary is displaying the fallback component but I see in the useErrorHandler code it has `if (error != null) throw error;` - which is triggering errors to get logged in the Chrome console and react throws it's own error `React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary2.`

Maybe I'm misunderstanding but is there a way to fully catch these errors? We want fallback UI etc but I thought the purpose of the error boundary was to catch errors and ensure they're handled and don't bubble up the entire app breaking it.

- `react-error-boundary` version: 3.1.4
- `node` version: 18.9.1
- `npm` version: 8.19.1

Relevant code or config

```js
// Our parent component has the error boundary:
<ErrorBoundary fallbackRender={FallbackOverlay}>
  <NavigationTree />
</ErrorBoundary>

// The nav tree code:
export const NavigationTree = (): JSX.Element => {
  const handleError = useErrorHandler()

  // Memo the tree confirm to ensure we only create it once
  const config = useMemo(() => ({
    data: async(): Promise<NodeConfigs> => {
      try {
        // Enable loading flag
        setIsTreeLoading(true)

        // Query data
        const { data } = await axios.get<NodeConfigs>('/mock/treenodes.jso') // intentionally wrong to test

        // Disable loading flag
        setIsTreeLoading(false)

        return data
      } catch (error) {
        handleError(error)
      }
    }
  }), [handleError])

  // Init the tree with memoized config
  const { tree } = useTree(config)

  return (
    <Overlay isLoading={isTreeLoading}>
      <div className={styles.treeViewport}>
        <Tree tree={tree} />
      </div>
    </Overlay>
  )
}
```

What happened:

```
Uncaught AxiosError {message: 'Request failed with status code 404', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
```

**Comment by viveleroi** [comment]
Maybe according to https://github.com/facebook/react/issues/15069 this is an issue with every error boundary approach... sigh

**Comment by bvaughn** [comment]
@viveleroi is right. This is React's default console logging behavior.
