### ISSUE TITLE
The ref attribute is not supported

### ISSUE THREAD

**Issue by StephewZ** [bvaughn/react-error-boundary#135]
Problem description:
// fake code

``` 
const ListComponent = React.forwardRef((props, ref) => {
    React.useImperativeHandle(ref, () => ({
        getData: () => console.log('1'),
        getList: () => console.log('2'),
    }));
    return <div></div>
});
const ListComponentWithErrorBoundary = withErrorBoundary(ListComponent);

// ListRef.current return undefined whent I use ErrorBoundary or withErrorBoundary
 const ListRef = useRef(null);
 useEffect(() => {
     console.log(ListRef.current)  // undefined
 }, [])
<ListComponentWithErrorBoundary ref={ListRef} />
```

**Comment by StephewZ** [comment]
"ref" doesn't work on the <ErrorBoundary ref={ref} /> component either

**Comment by bvaughn** [comment]
> "ref" doesn't work on the` <ErrorBoundary ref={ref} />` component either

I believe you're mistaken.

https://codesandbox.io/s/distracted-meadow-h0c97k

**Comment by StephewZ** [comment]
My mistake, it work in "ErrorBoudary"class component,but not work in withErrorBoundary.

**Comment by StephewZ** [comment]
yep，I also met this TypeScript issue, thx for your answer

**Comment by bvaughn** [comment]
Should work in 4.0.3

**Comment by genshinw** [comment]
> Should work in 4.0.3

I have the same issue. When will version 4.0.3 be released?

**Comment by bvaughn** [comment]
@genshinw 4.0.3 was released a week ago. You can see release versions on the NPM website (or using the `npm` CLI):

https://www.npmjs.com/package/react-error-boundary?activeTab=versions

**Comment by genshinw** [comment]
> @genshinw 4.0.3 was released a week ago. You can see release versions on the NPM website (or using the `npm` CLI):
> 
> https://www.npmjs.com/package/react-error-boundary?activeTab=versions

I only checked the release versions through the GitHub release page
