### ISSUE TITLE
Breaking change to FallbackProps type in v4

### ISSUE THREAD

**Issue by adamkovalsky** [bvaughn/react-error-boundary#138]
Prior to v4, the `error` property had the type `Error`:

https://github.com/bvaughn/react-error-boundary/blob/a0a370c7fe145e5cf169063eb4b7ff1a059fd84c/src/index.tsx#L6-L9

Whereas now it has the type `any`:

https://github.com/bvaughn/react-error-boundary/blob/7213c5416a70997bf24efe07de973b88b148902b/src/types.ts#L11-L14

The `args` of `resetErrorBoundary` also changed from `unknown[]` to `any[]`, but this change is less significant (although I do think `unknown[]` was a better choice).

The change of the `error` property is a breaking change though, is there a reason for this change?

**Comment by bvaughn** [comment]
Any value can be thrown in JavaScript- not just Errors. You can throw a string message, or even null or undefined. The new type is more accurate, given the throwing is in application code and not something this package can influence.

> The change of the error property is a breaking change though, is there a reason for this change?

Should be ok given it was a major revision? 😃

**Comment by adamkovalsky** [comment]
Thanks for the detailed explanation. Surely it's ok, I was just asking why the change happened as it wasn't mentioned anywhere.

Why choose `any` over `unknown` (which is the [default in strict mode](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/#use-unknown-catch-variables)), then?
