### ISSUE TITLE
Passing props to fallback component

### ISSUE THREAD

**Issue by wmonecke** [bvaughn/react-error-boundary#139]
How would I be able to pass props to the `fallbackRender` or `FallbackComponent`?

**Comment by bvaughn** [comment]
If you need to reference values that are in a local scope, the easiest way would be to use the `fallback` prop.

If for some reason you need to use a component instead, just return it from the `fallback` prop, e.g.

```js
<ErrorBoundary fallback={<YourFallback someProp={localVariable} />}>
  <ExampleApplication />
</ErrorBoundary>
```

**Comment by wmonecke** [comment]
Yup just figure it out. Thank you very much!

**Comment by wmonecke** [comment]
Is there a way to have both the error and the custom props?

**Comment by bvaughn** [comment]
Use the `fallbackRenderer` prop with an inline renderer (basically works the same as above).

**Comment by wmonecke** [comment]
Ah makes sense, awesome! Thank you!
