### ISSUE TITLE
'ErrorBoundaryContext not found' appears when using useErrorBoundary

### ISSUE THREAD

**Issue by daankennes** [bvaughn/react-error-boundary#142]
- `react-error-boundary` version: 4.0.4
- `node` version: 16.18.1
- `npm` version: 8.19.2

Relevant code or config

Simplified code:

```ts
import {ErrorBoundary, useErrorBoundary} from 'react-error-boundary';

export function SelectRouteScreen(props: Props) {
    const {showBoundary} = useErrorBoundary();

    const [routes, setRoutes] = React.useState<Route[]>();
    const [selectedRoute, setSelectedRoute] = React.useState<Route>();
    const [isRefreshing, setRefreshing] = React.useState(false);

    React.useEffect(() => {
        if (isRefreshing) {
            setRefreshing(true);
            fetchAndSetRoutes(session.username, setRoutes).catch((error) => {
                setRefreshing(false);
                showBoundary(error);
            });
        }
    }, [isRefreshing]);

    const renderRouteRow = (item: Route, index: number) => {
        return (
            <RouteRow
                route={item}
                index={index}
            />
        );
    };

    return (
        <ErrorBoundary
            onError={ErrorUtilities.errorBoundaryErrorHandler}
            fallback={<Text>Something went wrong!</Text>}
            onReset={() => setRefreshing(true)}>
            <PageWithHeader
                title={'title'}
                >
                <FlatListWithEmptyIndicator
                    isRefreshing={isRefreshing}
                    refreshControl={
                        <RefreshControl
                            refreshing={isRefreshing}
                            onRefresh={() => setRefreshing(true)}
                        />
                    }
                    data={isRefreshing ? null : routes}
                    renderItem={({item, index}) => renderRouteRow(item, index)}
                    keyExtractor={(item) => `routes${item.identifier}`}
                />
            </PageWithHeader>
        </ErrorBoundary>
    );
}


```

What you did:

Add the useErrorBoundary hook.

What happened:

Got 'ErrorBoundaryContext' not found.

![image](https://user-images.githubusercontent.com/32707088/236777988-7a0f2456-3b3f-47aa-99ae-dd5a346107cc.png)

Reproduction repository:

I cannot reproduce this in a fresh React Native project, so I am probably doing something wrong.

Problem description: 'ErrorBoundaryContext not found' error appears everywhere I try to use useErrorBoundary.

Suggested solution:

**Comment by daankennes** [comment]
Seems like I was confused about 'the nearest error boundary'. Is there a way to address the error boundary defined in the component itself (as I was trying to do in the code above) instead of the error boundary in the parent component?

**Comment by bvaughn** [comment]
Understandable confusion

> Is there a way to address the error boundary defined in the component itself

Unfortunately, no. React error boundaries work like try/catch- errors can only be caught when they’re thrown _inside of_ a try block. Same with error boundaries.

**Comment by bvaughn** [comment]
Just wrap your component in an error boundary– same as you would wrap code that might _throw_ an error in a try/catch.

The `withErrorBoundary` helper makes this very easy. In your case:

```js
export const SelectRouteScreen = withErrorBoundary(
  function SelectRouteScreen(props: Props) {
    // ...
```

**Comment by tirth1** [comment]
I'm getting **ErrorBoundaryContext not found** error. In my case parent is wrapped with ErrorBoundary component and the error is being thrown from child. Below is the code from where the error is being thrown. I also tried wrapping parent component with with withErrorBoundary, but no luck. 

@daankennes @bvaughn: can you help me here.
```
useEffect(() => {
 
    makeApiCall()
      .then((result) => {
      
      })
      .catch((error) => {
        if (condition) {
         throw error;
        }
 });
```

**Comment by bvaughn** [comment]
@tirth1 Not without a repro

**Comment by tirth1** [comment]
Sure, here is the simplified code.

App wrapped with ErrorBoundary
```

export const App = () => {
  return (
    <AppContexts>
      <Page
        header={<Header />}
        isManagedSidebar
        sidebar={<PageNav />}
        breadcrumb={<PageBreadCrumbs />}
        mainContainerId={mainPageContentId}
      >
        <ErrorBoundary
          FallbackComponent={ErrorRenderer}
          onReset={() =>
            (window.location.href =
              window.location.origin + window.location.pathname)
          }
        >
          <ChildComponent />
        </ErrorBoundary>
      </Page>
    </AppContexts>
  );
};

```

Child Component: throwing error

```

export const ChildComponent = () => {

const {showBoundary} = useErrorBoundary();

useEffect(() => {
 
    makeApiCall()
      .then((result) => {
      
      })
      .catch((error) => {
        if (condition) {
           showBoundary(error);
        }
 }, [deps]);

return (
    <Fragment>
          // code
    </Fragment>
);
}

```

**Comment by tirth1** [comment]
@bvaughn: here is the screenshot of error I'm getting.

<img width="1400" alt="image" src="https://github.com/bvaughn/react-error-boundary/assets/41485330/18b5c0bd-71fc-4088-886f-109c06d6d874">

**Comment by SimplySayHi** [comment]
> I'm getting **ErrorBoundaryContext not found** error. In my case parent is wrapped with ErrorBoundary component and the error is being thrown from child. Below is the code from where the error is being thrown. I also tried wrapping parent component with with withErrorBoundary, but no luck.
> 
> @daankennes @bvaughn: can you help me here.
> 
> ```
> const {showBoundary} = useErrorBoundary();
> 
> useEffect(() => {
>  
>     makeApiCall()
>       .then((result) => {
>       
>       })
>       .catch((error) => {
>         if (condition) {
>            showBoundary(error);
>         }
>  });
> ```

Same here.
With a simple app ( without context/apollo etc ) it works but in my app, that is quite complex it shows that error

**Comment by nordicgit70** [comment]
Same issue, but cannot reproduce within Nextjs template.
