### ISSUE TITLE
a friendlier default error component

### ISSUE THREAD

**Issue by graingert** [bvaughn/react-error-boundary#15]
react-error-overlay gives all sorts of nice details about the error.

A big red unhappy face lowers moral!

**Comment by bvaughn** [comment]
react-error-overlay runs within the larger context of create-react-app, and has more info to show in its (DEV mode only) overlay than this component would. All this component has is the information passed to `componentDidCatch` (an error message and a component stack).

If you'd like to put together a PR that shows this information in a better way, please feel free. I didn't assume anyone would use the built-in overlay to be honest. It's customizable for a reason. 😄

**Comment by graingert** [comment]
I used the default because it was the minimal amount of effort to get something working!

**Comment by kentcdodds** [comment]
We're dropping support for the default fallback.
