### ISSUE TITLE
[New feature request] add `ErrorBoundaryGroup` like @suspensive/react

### ISSUE THREAD

**Issue by manudeli** [bvaughn/react-error-boundary#154]
I want to make Pull Request to add ErrorBoundaryGroup in this library. ([ErrorBoundaryGroup](https://suspensive.org/docs/react/src/ErrorBoundaryGroup.i18n) is a component for managing multiple ErrorBoundaries at once in [@suspensive/react](https://suspensive.org/docs/intro/motivation.i18n))
I made documentation to show you what I want to add. and I want to check what you think of this before making Pull Request
https://suspensive.org/docs/react/src/ErrorBoundaryGroup.i18n

If you think this ErrorBoundaryGroup is a good idea, I'd like to request a chance for me to add this feature(ErrorBoundaryGroup).

**Comment by bvaughn** [comment]
I don't think I quite understand the use case for this feature. I think I understand the _concept_ (resetting multiple boundaries at once) but maybe not when that use case would come up in a real world application.

**Comment by bvaughn** [comment]
Closing due to lack of interest
