### ISSUE TITLE
4.0.11 cannot find module 'react-error-boundary' or its corresponding type declarations.

### ISSUE THREAD

**Issue by jlmn1026** [bvaughn/react-error-boundary#167]
- `react-error-boundary` version: 4.0.11
- `node` version:  20
- `pnpm` version: 8.7.4

Relevant code or config

```js
import * as React from 'react';
import { ErrorBoundary } from 'react-error-boundary';
```

What you did:
I  imported ErrorBoundary from  react-error-boundary.

What happened:
below error happenned.  
```
cannot find module 'react-error-boundary' or its corresponding type declarations.　
```

Reproduction repository:

Problem description:

When I downgraded to 3.1.4, this error resolved.

Suggested solution:

**Comment by bvaughn** [comment]
I think this sounds like an issue with your TS config.

Just to double check, here's a new project with v4.0.11 and it seems fine
https://codesandbox.io/s/sweet-lovelace-zjypk5
