### ISSUE TITLE
[Proposal] Detect an infinite loop of resetting the error

### ISSUE THREAD

**Issue by denis-sokolov** [bvaughn/react-error-boundary#168]
There are circumstances when an imperative resetErrorBoundary might be called in an infinite loop due to a mistake in the calling code. Consider, for instance, when we think we can automatically recover from an error, but we’re mistaken. In the code below, if `fixTheError` is mistaken, we will keep trying to re-render forever:

```js
function fallbackRender({ error, resetErrorBoundary }) {
  useEffect(() => {
    if (particularKindOf(error)) {
      fixTheError();
      resetErrorBoundary();
    }
  });
  return <div>{error.message}</div>;
}

<ErrorBoundary fallbackRender={fallbackRender} />;
```

It would be awesome, and possibly in scope of this project, if react-error-boundary in those cases would detect and avoid an infinite loop.

Example of how it could work:
1. Keep track of recently caught errors. Notice if we get 5+ errors with the same message in a second.
2. Turn resetErrorBoundary into a noop and stick with the last thrown error.
3. Output diagnostic information into the console about what happened.

**Comment by denis-sokolov** [comment]
Does the algorithm in the issue sound right to you? I’d like to avoid wasted effort.
> 1. Keep track of recently caught errors. Notice if we get 5+ errors with the same message in a second.
> 1. Turn resetErrorBoundary into a noop and stick with the last thrown error.
> 1. Output diagnostic information into the console about what happened.

**Comment by bvaughn** [comment]
TBH I haven't thought about the scenario in much detail so I can't promise anything.

Some things I would keep in mind:
1. Rendering is often async, so nothing should depend on a sync call stack.
2. There may be many error boundaries in a page and we should restrict this check to re-thrown errors within a single boundary (and possibly a time interval?)

**Comment by bvaughn** [comment]
Just doing some issue clean-up this morning and decided to close this one since it doesn't seem like it's going to be implemented. If you want to post a PR in the future though, please do.
