### ISSUE TITLE
How to customize error 

### ISSUE THREAD

**Issue by Tamir198** [bvaughn/react-error-boundary#170]
- `react-error-boundary` version:  4.0.10
- `node` version: v18.16.1
- `npm` version: 8.5.3

I was wondering if it's possible to send errors as a custom object.
For example - I have this hook that passes async code errors to the nearest error boundary: 

```js
  const { showBoundary } = useErrorBoundary();

  useEffect(() => {
    fetch("http://example.com/movies.json").then(
      (response) => {
        console.log(response);
      },
      (error) => {
        showBoundary(error);
      }
    );
  });
```

Is it possible to do something like this : 

```js
    (error) => {
        show boundary({title:error, message: "Custom message"});
     }
```

---

I tried it but seems like the second I create the simple object (for example `showBoundary({error})`) I will see this error in the console:

```js
[Uncaught ](react-error-boundary.esm.js:135 Uncaught)
```

![image](https://github.com/bvaughn/react-error-boundary/assets/34707669/2be106fd-814d-4d5b-bcf7-517d9595fea4)

---

This is my error boundary: 

```js
  <ErrorBoundary FallbackComponent={ErrorBoundaryFallback}>
    <React.StrictMode>
      <App />
    </React.StrictMode>
  </ErrorBoundary>
```

And the fallback component: 

```js
export const ErrorBoundaryFallback = ({ error }) => {
  return (
    <GlobalErrorModal
      isOpen={true}
      titleText={error.title}
      contentText={error.message}
      onClose={(): void => {}}
    />
  );
};
```

**Comment by bvaughn** [comment]
I don't think I have enough info to answer this question. Can you share a repro?

**Comment by Tamir198** [comment]
Don't have one but I can create one ,hope to update you soon with the link

**Comment by bvaughn** [comment]
Closing as not actionable.
