### ISSUE TITLE
NPM Install Fails with 404 for 'react-rerror-bounday' Package

### ISSUE THREAD

**Issue by anuragdeepxon** [bvaughn/react-error-boundary#171]
react-error-boundary version: (if applicable)
node version: 20.8.0
npm version: 9.6.7
Relevant code or config:
package.json snippet:

json
Copy code
"dependencies": {
  "react-rerror-bounday": "^4.0.4",
  // ... other dependencies
}
What you did:
Tried running npm install in the project directory.

What happened:
Received a 404 error for the package 'react-rerror-bounday'.

Full error message:

kotlin
Copy code
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-rerror-bounday - Not found
npm ERR! 404
npm ERR! 404 'react-rerror-bounday@^4.0.4' is not in this registry.
Reproduction repository:
(Link to a GitHub repository that reproduces the issue, if applicable)

Problem description:
NPM install fails due to a 404 error for 'react-rerror-bounday', which is listed in package.json. I suspect the package name is a typo and should be 'react-error-boundary'.

**Comment by anuragdeepxon** [comment]
<img width="857" alt="image" src="https://github.com/bvaughn/react-error-boundary/assets/99515330/b4dcd294-a556-46d1-adfd-2e458f068930">

**Comment by bvaughn** [comment]
Not really sure what this is reporting. Seems like a problem with some projects package json. I can’t help with that.

**Comment by michalm55** [comment]
@anuragdeepxon  you have typo in package name "react-rerror-bounday": "^4.0.4",

**Comment by anuragdeepxon** [comment]
Hi @michalm55 

Thanks, but that was not the issue.
I fixed this by changing this  "@types/react": "^17.0.60",

I was installing package by npm install react-error-boundary
I tried this too, pnpm add react-error-boundary
So error was not due to typo:


Here's the my package.json file
{
  "name": "anuragdeep.com",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "dependencies": {
    "@chakra-ui/react": "^2.8.1",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@hookform/resolvers": "^2.9.11",
    "@mui/material": "^5.14.11",
    "@mui/styled-engine-sc": "^5.14.11",
    "@mui/x-data-grid": "^6.16.0",
    "@mui/x-data-grid-generator": "^6.16.0",
    "@reduxjs/toolkit": "^1.9.5",
    "axios": "^0.27.2",
    "country-codes-list": "^1.6.10",
    "date-fns": "^2.30.0",
    "date-fns-tz": "^2.0.0",
    "dayjs": "^1.11.7",
    "framer-motion": "^10.16.4",
    "jwt-decode": "^3.1.2",
    "namor": "^3.0.1",
    "qrcode.react": "^3.1.0",
    "react": "^18.2.0",
    "react-blurhash": "^0.3.0",
    "react-country-region-selector": "^3.6.1",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.43.9",
    "react-parallax-tilt": "^1.7.160",
    "react-phone-input-2": "^2.15.1",
    "react-phone-number-input": "^3.2.23",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.11.0",
    "react-scripts": "5.0.1",
    "react-spinners": "^0.13.8",
    "react-table": "^7.8.0",
    "react-toastify": "^9.1.3",
    "styled-components": "^5.3.11",
    "swiper": "^9.3.2",
    "web-vitals": "^2.1.4",
    "yup": "^0.32.11",
    "yup-phone": "^1.3.2"
  },
  "scripts": {
    "dev": "vite",
    "build": "vite build && react-compress",
    "preview": "vite preview",
    "component": "generate-react component",
    "page": "generate-react component  --type=page",
    "redux": "generate-react component  --type=redux"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/react": "^17.0.60",
    "@types/react-dom": "^18.0.11",
    "@vitejs/plugin-react": "3.0.1",
    "@vitejs/plugin-react-swc": "^3.3.0",
    "eslint": "^8.39.0",
    "eslint-config-react-app": "^7.0.1",
    "generate-react-cli": "^7.3.0",
    "react-compress": "^3.6.4",
    "vite": "^4.3.1",
    "vite-plugin-eslint": "^1.8.1",
    "vite-plugin-svgr": "^2.4.0"
  }
}
