### ISSUE TITLE
Preventing React unmounting UI on error?

### ISSUE THREAD

**Issue by JamesBrightman-pp** [bvaughn/react-error-boundary#172]
React v18.2.0
react-error-boundary v4.0.11

I've written an error boundary and wrapped it at my webapp's base level. This is now catching errors and displaying a `FallbackComponent` properly. 
My issue is that whenever there is an error that is thrown to the error boundary, React will unmount all the UI so I'm left with a blank white page plus FallbackComponent. Is there a way to change this? Ideally what I want is for the FallbackComponent to rendered on top of the webapp, and the webapp to not be unmounted. Please advise if this is possible or if I'm misusing this library, thanks.

**Comment by bvaughn** [comment]
That behavior isn't supported by this library. You could try to implement it directly, with your own error boundary (not this library) but it would be tricky as any error thrown would likely break the UI.

**Comment by bvaughn** [comment]
It could be possible, but I think you would have to re-rendeer with the previous props and state so as to avoid the error and it seems complicated.

Ultimately, you could grab a DOM/HTML?
