### ISSUE TITLE
useErrorBoundary as global

### ISSUE THREAD

**Issue by szylmzs** [bvaughn/react-error-boundary#173]
how to use useErrorBoundary as global

**Comment by bvaughn** [comment]
It's a hook. Only meant to be used as a hook. I don't know what you mean by "global" but here is the usage docs:
https://github.com/bvaughn/react-error-boundary#useerrorboundary-hook

**Comment by szylmzs** [comment]
> It's a hook. Only meant to be used as a hook. I don't know what you mean by "global" but here is the usage docs: https://github.com/bvaughn/react-error-boundary#useerrorboundary-hook

thanks, I see, I should use it manually where needs it
