### ISSUE TITLE
Bug with catching errors when using React Router

### ISSUE THREAD

**Issue by KristianKjerstad** [bvaughn/react-error-boundary#177]
- `react-error-boundary` version: 4.0.12
- `node` version: v20.7.0
- `npm` version: 10.1.0

Additional:
- react router version: 6.21.1
- react: 18.2.0

Relevant code or config

```js
// main.tsx -  entry point for app:
<ErrorBoundary fallback={<div>Something went wrong...</div>}>
    <App />
</ErrorBoundary>

//
//

// inside App.tsx
function App() {
    return (
        <Routes
            <Route
                path="/recipe/:id"
                element={
                    <ErrorBoundary fallback={<div>Error in router</div>}>
                        <RecipePage />
                    </ErrorBoundary>
                }
            />
            <Route path="*" element={<ErrorPage />} />
        </Routes>
    )
}

//
//

// inside RecipePage.tsx


export const RecipePage = () => {
    const { id: recipeId } = useParams()
    
    const [recipe, setRecipe] = useState<Recipe | undefined>(getRecipe(...))
   // stuff ....
    return (
            <div>
                <h1>{recipe.name}</h1>
                <ErrorBoundary
                      fallback={<div>Could not display recipe instructions...</div>}
                  >
                <div>
                    {recipe.recipe_steps?.map((instruction, index) => {
                        throw new Error('some error')
                        return (
                            <div key={index}>
                                {index + 1}. {instruction}
                            </div>
                        )
                    })}
                </div>
            </div>
        </ErrorBoundary>
    )
}
```

What you did:
Ran the application

What happened:

The ErrorBOundary in App.tsx catches the error

Reproduction repository:

Problem description:

The "inner most" ErrorBoundary in RecipePage.tsx should catch the error instead of the ErrorBoundary in App.tsx

Suggested solution:
??

**Comment by bvaughn** [comment]
This is a somewhat common misunderstanding.  Error boundaries work kind of like `try`/`catch` blocks, so I can see why you might assume that the above code should work. The error thrown in your example isn't really "inside" of the `try` block though, it's more like this:
```js
try {} catch (error) {}

throw Error(...);
```

To understand why this is the case requires a bit of a deeper understanding of React and JSX.

People typically write React using JSX. The browser doesn't understand JSX, so this gets "compiled" to regular JavaScript. For example:
```js
// JSX
<ErrorBoundary>
  <YourComponent />
</ErrorBoundary>

// Compiled JavaScript
import { jsx as _jsx } from "react/jsx-runtime";
_jsx(ErrorBoundary, {
  children: _jsx(YourComponent)
});
```

React works with the tree of elements created by the JSX by traversing it top-down. In the example above, React will create an instance of the `ErrorBoundary` component and render it (call `.render()`), then it will do the same for `YourComponent`. If `YourComponent` throws an error while rendering, React will pass that error to the `ErrorBoundary` parent.

The scenario you're reporting is different though. It is more like this:
```jsx
// JSX
<ErrorBoundary fallback="Error">
  {array.map((value) => {
    throw Error("Example");
  })}
</ErrorBoundary>

// Compiled JavaScript
import { jsx as _jsx } from "react/jsx-runtime";
_jsx(ErrorBoundary, {
  children: _jsx("div", {
    fallback: "Error",
    children: array.map(value => {
      throw Error("Example");
    })
  })
});
```

This script will throw an error _before_ the `jsx` function even runs– before the error boundary has even been created or rendered. So React won't be able to use the boundary you're defining here. It will go to the next higher one instead (if there is one).
