### ISSUE TITLE
`fallback` function is not allowing to render `ReactPortal` via `createPortal()` function

### ISSUE THREAD

**Issue by bayraak** [bvaughn/react-error-boundary#178]
- `react-error-boundary` version: 4.0.12
- `node` version: 20.9.0
- `npm` version: 10.1.0

Relevant code or config

```tsx
    <ErrorBoundary
    fallback={createPortal(
                <div>It works!</div>,
                document.getElementById('top-feedback-banner-container')
            )}
    >
      {children}
    </ErrorBoundary>
```

Problem description:

I would expect React Portal's work with any of the fallback methodologies but obviously, it is not supported. As a fallback UI, I don't need to replace the whole page's UI but mutate an HTML element via React's `createPortal` feature.  

Suggested solution:

I've checked the code of the library and I see that <ErrorBoundary /> always creates a new React element with `createElement`. Probably that's the issue that is not allowing to render Portal's

**Comment by bvaughn** [comment]
> I've checked the code of the library and I see that always creates a new React element with createElement. Probably that's the issue that is not allowing to render Portal's

I'm not sure I understand this comment. React works with elements. New elements (objects with a predefined set of attributes describing component type and props) are created every render, and React has logic to diff them to the previous elements to determine whether an update is required.

I don't generally spend much time trying to debug errors that don't include a full repro case. Partial code snippets require me to spend time filing in the missing pieces and sometimes the problem ends up being in those missing pieces.

**Comment by bvaughn** [comment]
> As a fallback UI, I don't need to replace the whole page's UI but mutate an HTML element via React's createPortal feature.

I will say that this isn't how React works with error boundaries. React _removes_ the error content and _replaces it_ with the fallback UI. (That's not something this library has any control over).

I suppose you could try to copy the DOM's inner HTML on error and reset it, but any components on the page would not be interactive so that approach seems kind of fraught.

**Comment by bvaughn** [comment]
Anyway to "fix" this error, wrap your portal in a component, e.g.:
```jsx
function Fallback() {
  return createPortal(
    <div>...</div>,
    document.getElementById("portal")
  );
}
```
Then reference it like so:
```jsx
<ErrorBoundary fallback={<Fallback />}>
```

Demo here:
https://codesandbox.io/p/sandbox/withered-rgb-psqf42?file=%2Fsrc%2FApp.js%3A9%2C5-9%2C44
