### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by andresliu-p202** [bvaughn/react-error-boundary#184]
- `react-error-boundary` version: 4.0.13
- `node` version: 20.11.1
- `npm` version: 10.2.4

Relevant code or config

N/A

What you did: N/A

What happened: N/A

Reproduction repository: N/A

Problem description: Hello. We'd like to use this package but did not find any documentation regarding browser compatibility, our use case requires our app to be backwards compatible with at least Chrome version 64. Do you think there will be any issues?

Suggested solution: N/A

**Comment by bvaughn** [comment]
This component has no rendering code in it. You can use it with React DOM, React Native, etc. (There are no browser dependencies)
