### ISSUE TITLE
Using `useEffect` inside of `fallbackRender` not working

### ISSUE THREAD

**Issue by mechaniccoder** [bvaughn/react-error-boundary#188]
- `react-error-boundary` version: 4.0.13
- `node` version: 18
- `npm` version: 10

Using `FallbackComponent` and `useEffect` -> Working ✅
```js
const Fallback = ({ error, resetErrorBoundary }) => {
  useEffect(() => {}, []);

  return (
    <div role="alert" className="error">
      <h1>Error</h1>
      <h2>{error.toString()}</h2>
      <button onClick={resetErrorBoundary}>Reset Error</button>
    </div>
  );
};


<ErrorBoundary FallbackComponent={Fallback}>
  <App />
</ErrorBoundary>
```

Using `fallabckRender` and `useEffect` -> Error ❌
```js
const Fallback = ({ error, resetErrorBoundary }) => {
  useEffect(() => {}, []);

  return (
    <div role="alert" className="error">
      <h1>Error</h1>
      <h2>{error.toString()}</h2>
      <button onClick={resetErrorBoundary}>Reset Error</button>
    </div>
  );
};

<ErrorBoundary FallbackComponent={Fallback}>
  <App />
</ErrorBoundary>
);
```

Reproduction repository:

[code sandbox example](https://codesandbox.io/p/sandbox/error-boundary-632csl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clysr9ceh00063b6pot9zpcwv%2522%252C%2522sizes%2522%253A%255B60%252C40%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clysr9ceh00023b6pa8zc82us%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clysr9ceh00033b6pva4y96ai%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clysr9ceh00053b6pngvunp4c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clysr9ceh00023b6pa8zc82us%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clysr9ceg00013b6p70xd2q28%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clysr9ceh00023b6pa8zc82us%2522%252C%2522activeTabId%2522%253A%2522clysr9ceg00013b6p70xd2q28%2522%257D%252C%2522clysr9ceh00053b6pngvunp4c%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clysr9ceh00043b6p699rfc63%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clysr9ceh00053b6pngvunp4c%2522%252C%2522activeTabId%2522%253A%2522clysr9ceh00043b6p699rfc63%2522%257D%252C%2522clysr9ceh00033b6pva4y96ai%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clysr9ceh00033b6pva4y96ai%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Problem description:

When using `useEffect` inside of `fallbackRender`, error UI does not render but when using `useEffect` inside of `FallabckComponent`, it works. Why this error happens??

**Comment by bvaughn** [comment]
FallabckComponent is a React element (and so it supports things like hooks); fallabckComponent is a “render prop” (lighter weight) and doesn’t support hooks

**Comment by karfau** [comment]
I think this is not really obvious from the readme.
Can I suggest adding a sentence to the section about the hook or to add an FAQ entry?
I can also provide a pull request, in which I could also include some doc strings for the hook and the type of it's return value.

**Comment by bvaughn** [comment]
@karfau Happy to review a PR if you'd like to propose changes to the docs :)

**Comment by karfau** [comment]
To make sure I get the wording right:
The hook always goes to the closest error boundary, independent which kind of fallback it has, right?
So even if you have a top level one with a FallbackComponent but between that one and the component that uses the hook, there is another one not using FallbackComponent, it would attempt to use the hook inside of the closer one, which would fail complaining about the rules for hooks, which would than be rendered by the next error boundary after the closest one?

**Comment by bvaughn** [comment]
It goes to the nearest boundary and tries again. If that one fails/throws, it will go to the next nearest boundary. Conceptually it's like this:

```js
try {
  try {
    // This is like the original error
    throw "first error";
  } catch (error) {
    // This is like the nearest boundary catching the 1st error but then also failing
    throw "second error";
  }
} catch (error) {
  // This is the next boundary catching the 2nd error
}
```
