### ISSUE TITLE
a redundant error generated by showBoundary

### ISSUE THREAD

**Issue by benhuangbmj** [bvaughn/react-error-boundary#189]
- `react-error-boundary` version: 4.0.13
- `node` version:
- `npm` version:

Relevant code or config

```js
showBoundary(err)
```

What you did: I call showBoundary on an error.

What happened: It generates an uncaught error.

Reproduction repository:

Problem description: Whenever I call the showBoundary function on an error, the same error will be reproduced and thrown, and an uncaught error message will show in the console.

Suggested solution: I believe the reproduced error is generated by the code in line 39-41 in src/useErrorBoundary.ts. I am not sure what purpose these lines serve. I suggest remove them from the file.

**Comment by bvaughn** [comment]
I am going to close this issue because there is not enough info for me to help with.

Please provide a repro case that I can run and look at, as well as the actual error text and call stack that is thrown and I will re-open this issue.

**Comment by benhuangbmj** [comment]
> I am going to close this issue because there is not enough info for me to help with.
> 
> Please provide a repro case that I can run and look at, as well as the actual error text and call stack that is thrown and I will re-open this issue.

Thank you for the reply. I have made a [Codesandbox demo](https://codesandbox.io/p/sandbox/show-error-boundary-vk6vgp) to illustrate the issue. I now understand that lines 39-41 in *src/useErrorBoundary.ts* are crucial for the `ErrorBoundary` to function properly. Is there a built-in mechanism in **react-error-boundary** to suppress the display of uncaught error messages after calling `showBoundary`? If not, and if you think this would enhance the developer experience, I’d be happy to work on a solution. Thanks!

**Comment by bvaughn** [comment]
> Is there a built-in mechanism in react-error-boundary to suppress the display of uncaught error messages after calling showBoundary? 

Are you referring to the DEV mode overlay (in the picture below)?
![Screenshot 2024-08-01 at 5 00 19 PM](https://github.com/user-attachments/assets/d61ca6b5-9619-4b06-9b22-e014e3c0a688)

If so, then no. That's not something react-error-boundary does, and it's intentional (but it's only shown in DEV builds).

**Comment by benhuangbmj** [comment]
> > Is there a built-in mechanism in react-error-boundary to suppress the display of uncaught error messages after calling showBoundary?
> 
> Are you referring to the DEV mode overlay (in the picture below)? ![Screenshot 2024-08-01 at 5 00 19 PM](https://private-user-images.githubusercontent.com/29597/354381856-d61ca6b5-9619-4b06-9b22-e014e3c0a688.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDY5MDksIm5iZiI6MTcyMjU0NjYwOSwicGF0aCI6Ii8yOTU5Ny8zNTQzODE4NTYtZDYxY2E2YjUtOTYxOS00YjA2LTliMjItZTAxNGUzYzBhNjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDIxMTAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZWExODMzM2RmODFlOGQyYTA4N2IwODcyZTJiYzNhZDIwZTcxY2RhMTlmNjA1N2Q0MTBiMTM0NDgxMmY4ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6BIjm1zZVn25wbF79WNMma0LOorj4EQPEKGyxeInF8w)
> 
> If so, then no. That's not something react-error-boundary does, and it's intentional (but it's only shown in DEV builds).

Thank you for the prompt reply. No, it's not the DEV overlay that I am concerned about. I understand that this overlay was generated by Codesandbox. What I was referring to is the error message in the console: 
![console](https://github.com/user-attachments/assets/685b8170-f2bc-436c-9973-c430e1f423a1)

I also understand that typically this would not affect the functionality of the app, but it may have some minor impact on the DX. I dug around a little bit and learned that they were generated by the browser and React respectively. I have a rough idea of how to get rid of them. If you think it's worthwhile, I can make a pull request for your review. Thanks.

**Comment by bvaughn** [comment]
Ah, those console errors are also an intentional decision (for React, DEV mode). I don't think I'd want to try to work around them here.

**Comment by benhuangbmj** [comment]
> Ah, those console errors are also an intentional decision (for React, DEV mode). I don't think I'd want to try to work around them here.

I agree that it serves a purpose. But in the particular case that the errors are generated by `showBoundary`, it's by assumption already been caught in the code. In addition, if there is already some handling passed to the `onError` prop, the console errors may seem duplicate/redundant or even confusing. What do you think?

**Comment by bvaughn** [comment]
If you have an idea, submit a PR and I'll be happy to take a look and consider it.

**Comment by benhuangbmj** [comment]
> If you have an idea, submit a PR and I'll be happy to take a look and consider it.

Sounds awesome. Thank you for the consideration!
