### ISSUE TITLE
Error while bundling with Vite.js

### ISSUE THREAD

**Issue by AnoNate** [bvaughn/react-error-boundary#190]
- `react-error-boundary` version: 4.0.13
- `node` version: 20.5.1
- `npm` version: 10.8.2

Relevant code or config

```js

```

What you did:
bundled my app using vite.js — version 5.2.11

What happened:

Got an error while bundling my app with Vite.js - see screenshot:
<img width="761" alt="Screenshot 2024-08-05 at 10 27 22 AM" src="https://github.com/user-attachments/assets/1756661f-9151-43e5-a3b6-f6bf44b0b1fa">

Reproduction repository:

Problem description:  See above

Suggested solution:  Remove any module level directives.

**Comment by bvaughn** [comment]
> Suggested solution: Remove any module level directives.

I don't think this is a viable solution, at least to my knowledge. This directive is required to work with [React Server Components](https://react.dev/learn/start-a-new-react-project#bleeding-edge-react-frameworks).

**Comment by AnoNate** [comment]
Got it.  My stack is Laravel / Inertia.js / React.js, so I am not using node.js, Next.js or any javascript based server side.  I don't know if this is a serious error, but I will report back if so.  In any case I am very happy with your package as the built-in React Error Boundary did not work with my stack, but yours does (in development at least — pre bundle).

Perhaps it might be possible to add an option for users that use React with a traditional MVC server side framework?

**Comment by bvaughn** [comment]
I'm open to suggestions if you have something concrete. (Truthfully it's not very high priority to me though so I'm unlikely to look into it myself)

**Comment by AnoNate** [comment]
Ok, thanks. If it turns out to be a serious issue I will research it and get back to you if I come up with a possible solution.  Looks like you don't have many users of your package that work with the Vite.js bundler, otherwise perhaps it might be a higher priority.

**Comment by bvaughn** [comment]
Going to close this issue for now since it doesn't seem likely to be picked up.
