### ISSUE TITLE
[question] alternatives to using resetKeys

### ISSUE THREAD

**Issue by janeklb** [bvaughn/react-error-boundary#192]
_(this is not a bug.. it's a question that stems from your / @bvaughn's comment here: https://github.com/bvaughn/react-error-boundary/pull/131#issuecomment-2324737773)_

Would you recommend an alternative approach to using `resetKeys` in the following scenario.

```jsx

const ComponentThatThrows = ({ value }) => {
  if (value === "error") {
    throw new Error("Bang!")
  }
  return `Thanks, you provided: '${value}'`;
}


const ComponentWithErrorBoundary = ({ value }) => {
  return (
    <div>
      <ErrorBoundary fallback={<span>Oooops!</span>} resetKeys={[value]}>
        <ComponentThatThrows value={value} />
      </ErrorBoundary>
    </div>
  );
};

const Example = () => {

  const [externalState, setExternalState] = React.useState();
  const onChange = React.useCallback((event) => setExternalState(event.target.value), []);
  
  return (
    <div>
      Type something: <input onChange={onChange} />
      <ComponentWithErrorBoundary value={externalState} />
    </div>
  );
};

```

see https://jsfiddle.net/janeklb/t5o7dbsc/ for fiddle

If `ComponentWithErrorBoundary` receives `{ value: 'error' }` as props, then one of it's children (`ComponentThatThrows`) will throw, causing the error boundary to render the fallback. If I'd want `ComponentWithErrorBoundary` to try and re-render it's children, the simplest way I can think of doing it is to use `resetKeys`; can you recommend anything else?

**Comment by bvaughn** [comment]
I'm not sure I understand this question. Is `resetKeys` not working for you? It seems like it is doing what (I assume) you want, in which case– it seems fine to keep using it.

**Comment by janeklb** [comment]
`resetKeys` is working for me. Sounds like I misunderstood [your comment](https://github.com/bvaughn/react-error-boundary/pull/131#issuecomment-2324737773)

> `resetKeys` is not functionality I have ever used or care much about, but it's still here
