### ISSUE TITLE
Element ErrorBoundary doesn't have required attribute fallback

### ISSUE THREAD

**Issue by Tsyklop** [bvaughn/react-error-boundary#193]
- `react-error-boundary` version: 4.0.13
- `node` version: 22.2.0 
- `npm` version: pnpm 9.11.0

Relevant code or config

```js
import { ErrorInfo, PropsWithChildren } from "react";
import { ErrorBoundary, type FallbackProps } from "react-error-boundary";

import { UiAlert, UiButton, UiText } from "../kit";

const Error = ({ resetErrorBoundary }: FallbackProps) => {
  return (
    <UiAlert variant="error" title="Component Error!">
      <UiText variant="body-3-medium">Something went wrong. Please refresh the page or contact support if the issue persists.</UiText>
      <UiButton onClick={() => resetErrorBoundary()}>Try again</UiButton>
    </UiAlert>
  );
};

export const UiErrorBoundary = (props: PropsWithChildren) => {
  return (
    <ErrorBoundary onError={(error: Error, info: ErrorInfo) => console.error(error, info)} FallbackComponent={Error}>
      {props.children}
    </ErrorBoundary>
  );
};
```

What you did:
I created my component with `ErrorBoundary`. 

What happened:

I got the error:
![image](https://github.com/user-attachments/assets/da430d4c-381c-4343-ab80-168fbb2d321b)

**Comment by bvaughn** [comment]
Not sure why you’re getting that TypeScript error. Maybe it’s the version of TypeScript you’re using?

From what I can see it a glance, the code you shared looks like it should be fine.

**Comment by bvaughn** [comment]
Not sure. Can you repro this error in the [TypeScript playground](https://www.typescriptlang.org/play/)?
