### ISSUE TITLE
Breaking change for node versions < 20

### ISSUE THREAD

**Issue by sahariko** [bvaughn/react-error-boundary#201]
- `react-error-boundary` version: 4.1.0
- `node` version: 18.12.1
- `npm` version: 8.19.2

What you did:
Upgraded from version `4.0.3` to `4.1.0`

What happened:

```
error react-error-boundary@4.1.0: The engine "node" is incompatible with this module. Expected version ">=20". Got "18.12.1"
```

Problem description:
Version `4.1.0` inadvertently [introduced a breaking change with the addition of the `engines` field](https://github.com/bvaughn/react-error-boundary/commit/206bdbad362737480ebd39cefb945c8cec11c1ce#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R12) to `package.json`.
Up until this point this package worked fine with versions of node older than 20.

Suggested solution:
Reduce the `engines`'s node version demand.

**Comment by bvaughn** [comment]
I’m not sure I understand why that setting affects your package. Unless you were trying to build it from source, I don’t understand why the engines setting would impact you?

**Comment by onethread** [comment]
Getting the same. Yarn is throwing an error for me. 

<img width="824" alt="Screenshot 2024-10-16 at 09 50 40" src="https://github.com/user-attachments/assets/4f35095e-2c1e-4eb3-950e-748076c1cc1b">

**Comment by sahariko** [comment]
> I’m not sure I understand why that setting affects your package. Unless you were trying to build it from source, I don’t understand why the engines setting would impact you?

@bvaughn my project is failing during installation, specifically when running `yarn install`.

**Comment by christinna9031** [comment]
Can confirm we're getting the exact same error.

**Comment by bvaughn** [comment]
That's interesting. I wouldn't have expected that since there's no postinstall script or anything 🤔  Hmm. I will roll that change back.

**Comment by bvaughn** [comment]
Sorry about this, folks. Hopefully react-error-boundary@4.1.1 resolves this issue for everyone?

**Comment by Frecherenkel60** [comment]
> I’m not sure I understand why that setting affects your package. Unless you were trying to build it from source, I don’t understand why the engines setting would impact you?

The engines field imposes restrictions on consumers ([docs](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines)). On another note, could you also please remove the requirement for `pnpm`? We're still using `yarn` (unluckily) and get warnings during install.

```
 warning react-error-boundary@4.1.0: The engine "pnpm" appears to be invalid.
```

**Comment by bvaughn** [comment]
The `"engines"` block _helps me_ keep my own PNPM versions straight (so I'm not clobbering my lock files when switching between projects). I should probably find a better way to do this but I'm struggling to have enough time to maintain my open source projects on top of my day job and I'm not sure when I'll get to it.

What you're reporting here is a Yarn v1 bug. Yarn should not be warning about other engines. You can silence the warning for yourselves though by adding the following lines to your `.yarnrc`:
```
ignore-engines pnpm
```

**Comment by Frecherenkel60** [comment]
> The `"engines"` block _helps me_ keep my own PNPM versions straight (so I'm not clobbering my lock files when switching between projects). I should probably find a better way to do this but I'm struggling to have enough time to maintain my open source projects on top of my day job and I'm not sure when I'll get to it.
> 
> What you're reporting here is a Yarn v1 bug. Yarn should not be warning about other engines. You can silence the warning for yourselves though by adding the following lines to your `.yarnrc`:
> 
> ```
> ignore-engines pnpm
> ```

Wow, I completely misunderstood the concept of the `engines` field then, sorry for that.

**Comment by bvaughn** [comment]
No, I'm pretty sure that I misunderstood it (at least the _scope_ of it). I didn't think it would impact anything other than if you were executing package scripts within the repo. As this issue has shown me, it affects installs as well 😭 

I'm really sorry that it caused this issue for others, and I'd like to fix it, I just don't have as much free time as I used to 🙇🏼  I appreciate everyone being patient.

**Comment by Frecherenkel60** [comment]
> No, I'm pretty sure that I misunderstood it (at least the _scope_ of it). I didn't think it would impact anything other than if you were executing package scripts within the repo. As this issue has shown me, it affects installs as well 😭
> 
> I'm really sorry that it caused this issue for others, and I'd like to fix it, I just don't have as much free time as I used to 🙇🏼 I appreciate everyone being patient.

Well, if it's only about keeping your PNPM versions straight, you should probably enable corepack. You can specify a `packageManager` field in your `package.json` where you can pin your versions without affecting your consumers. Here's the according [documentation](https://nodejs.org/docs/latest-v20.x/api/corepack.html#corepack). :)

**Comment by bvaughn** [comment]
Hmm, Corepack is still experimental isn't it? Either way, until I've done that in all of my projects, it seems like it's too easy to _forget_ to use it and just run `pnpm` directly (which I think would just "work")

**Comment by Frecherenkel60** [comment]
Well, yeah. It is still experimental and there are still vivid [discussions](https://github.com/nodejs/node/issues/50963?utm_source=nodeland&utm_medium=email&utm_campaign=which-http-client-for-nodejs-should-nodejs-stop) about the future of it. In my experience it is still worth to use it, because it simplifies the development of multiple projects on the same device without a lot of effort. 

Basically you would only need to set the `packageManager` field in the `package.json` of every project you're using and run `corepack enable` once per node version. The rest will be handled by corepack in a predictable fashion as outlined in their docs:

- If the packageManager field is populated in a project and you have the version installed it will directly use it
- If the packageManager field is populated in a project and you don't have the version installed it will ask you to download it
- If the packageManager field is not populated in a project it will use a "[known good release](https://github.com/nodejs/corepack#known-good-releases)"
