### ISSUE TITLE
[Suggestion] From fallbackRender to renderFallback

### ISSUE THREAD

**Issue by hnordt** [bvaughn/react-error-boundary#210]
The prop name `fallbackRender` doesn’t feel quite right to me, it seems a bit off.

What do you think about changing it? I’d be happy to open a PR if you agree! Here are a couple of ideas:

1. Remove `fallbackRender` entirely and allow passing a function to `fallback` instead.
2. Rename `fallbackRender` to `renderFallback`, which feels more natural and aligns better with React Native conventions like `renderItem`.

Let me know your thoughts! 😊

**Comment by bvaughn** [comment]
Naming is subjective. I appreciate the feedback, but I would prefer not to rename this prop. It’s been named this for years and it isn’t worth requiring a major version bump to change it.

Thank you though!

**Comment by hnordt** [comment]
@mnmnk43434 If the idea is approved, we must still support the `fallbackRender` option and simply deprecate it.
