### ISSUE TITLE
Feature Request: Provide a way to clear the error

### ISSUE THREAD

**Issue by dance2die** [bvaughn/react-error-boundary#23]
# What?
Would you provide a way to clear the error in [ErrorBoundary](https://github.com/bvaughn/react-error-boundary/blob/master/src/ErrorBoundary.js) component to clear the `FallbackComponent` ?

# Suggestion

If [error](https://github.com/bvaughn/react-error-boundary/blob/master/src/ErrorBoundary.js#L29) state can be set via prop, one should be able to clear it depending on outter component's state.
Right now, there is no way to get around the ErrorBoundary without the following workaround

# Workaround
A workaround I used is to create a ref assigned to the `ErrorBoundary` and cleared in `onStepClick`.

```javascript
class Wizard extends Component {
  errorBoundary = React.createRef();

  // redacted unrelevant code...
  
  onStepClick = current => {
    this.errorBoundary.current.state.error = null;
  };

  
  render() {
    const { current } = this.state;

    return (
      <div>
        <Steps current={current}>
          {steps.map((item, step) => (
            <Steps.Step
              key={item.title}
              onClick={e => this.onStepClick(step)}
            />
          ))}
        </Steps>
        <div className="steps-content">
          <ErrorBoundary
            ref={this.errorBoundary}
            FallbackComponent={ErrorFallbackComponent}
          >
            {this.getContent()}
          </ErrorBoundary>
        </div>
      </div>
    );
  }
}
```

# Demos

I've created a [SandBox demo](https://codesandbox.io/s/6n4n6xkv3) for the demonstration.

[![Edit demo-cant-clear-react-error-boundary-error](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6n4n6xkv3)

& Here is the link to the [video](https://youtu.be/U54GE0jrrAA) of how the demo works.

**Comment by dance2die** [comment]
added `suggestion`

**Comment by bvaughn** [comment]
This is not a safe thing to do by the way 😄
```js
this.errorBoundary.current.state.error = null;
```
React sets/resets `instance.error` while rendering and manually updating state is not supported because it will be erased by a future render. The only way to safely update state is with `setState`. (State is also meant to be internal to the component, not set by a parent in this way.)

The way I would recommend resetting this error boundary (if you really want to blow away the error) would be to just clear it out using a new `key` value. For example:
https://codesandbox.io/s/k9znx9kj9r

This will tell React to throw out the previous instance (with its error state) and replace it with a new instance.

**Comment by dance2die** [comment]
Thanks Brian.
Using the `key` value certainly is a React way of handling.

I was able to get it working now without that hackity hack (`ref`) 😄 
https://github.com/dance2die/bunpkg-client/blob/master/src/container/Wizard.js#L133

**Comment by osener** [comment]
@bvaughn how about passing `() => this.setState({ error: null })` callback to FallbackComponent? This would make it easy to render a <kbd>Retry</kbd> button without introducing state to the component.

**Comment by bertho-zero** [comment]
This component is used exactly like react-error-boundary but with an additional `retry` props.

```js
// ErrorBoundary.js

import React, { useState, useCallback } from 'react';
import ReactErrorBoundary from 'react-error-boundary';

export default function ErrorBoundary({ children, FallbackComponent, ...props }) {
  const [key, setKey] = useState(1);
  const retry = useCallback(
    () => setKey(state => state + 1),
    [setKey]
  );
  const FallbackWithRetryComponent = useCallback(
    fallbackProps => <FallbackComponent {...fallbackProps} retry={retry} />,
    [retry]
  );

  return (
    <ReactErrorBoundary key={key} {...props} FallbackComponent={FallbackWithRetryComponent}>
      {children}
    </ReactErrorBoundary>
  );
}

```
