### ISSUE TITLE
Use new static getDerivedStateFromError()

### ISSUE THREAD

**Issue by avdeev** [bvaughn/react-error-boundary#24]
Subj

https://reactjs.org/docs/react-component.html#static-getderivedstatefromerror

**Comment by bvaughn** [comment]
This would require a backwards-breaking release. May be worth supporting at some point in the future (once updating state from `getDerivedStateFromProps` is actually deprecated, `getDerivedStateFromError` is supported by the server renderer, and v16.6+ has wider adoption) but I don't think it's high enough value to do for now. Errors are rare, and I don't think we need to worry too much optimize the fallback rendering in this case
