### ISSUE TITLE
Error type is unknown, not `Error`?

### ISSUE THREAD

**Issue by OliverJAsh** [bvaughn/react-error-boundary#25]
In the types, the error is typed as `Error`. However, in JS any type can be thrown, e.g. `throw "foo";`.

Should we correct the type of the error to `unknown` (in TypeScript terms), or is there something that converts it to an `Error`?

**Comment by bvaughn** [comment]
Yeah, seems reasonable.

**Comment by OliverJAsh** [comment]
I'm not familiar with Flow so I'm not quite sure what the equivalent to TypeScript's `unknown` type is?

**Comment by bvaughn** [comment]
`any`

**Comment by kentcdodds** [comment]
Closing all old issues as we're making significant changes. Please open a new issue if this is still a problem you'd like to have fixed.

**Comment by tommarien** [comment]
@OliverJAsh This should have been fixed in version  >= 3.1.3
