### ISSUE TITLE
<Unknown></Unknown> created withErrorBoundary with HOC

### ISSUE THREAD

**Issue by vsravan707** [bvaughn/react-error-boundary#27]
withErrorBoundary HOC, an <Unknown></Unknown> is created.
Convention: Wrap the Display Name for Easy Debugging

**Comment by bvaughn** [comment]
Submit a PR if you'd like to see this change. 😄

**Comment by vsravan707** [comment]
Hi Brian Vaughn,
Thank you very much for "react-error-boundary", I created pull request.
