### ISSUE TITLE
ErrorBoundaryFallbackComponent is unnecessary

### ISSUE THREAD

**Issue by blling** [bvaughn/react-error-boundary#3]
Users will not use the `ErrorBoundaryFallbackComponent` most of the time, so we can remove it from core lib and put it in a separeted showcase ?

**Comment by bvaughn** [comment]
That component can be dead-code eliminated from any production app that uses this library _without_ using it, so I don't see the harm in leaving it? It's also tiny. 😄

**Comment by bvaughn** [comment]
I think I'm going to leave it in for my own convenience (one less project to maintain and sync) and b'c I don't think it's much of a problem, given my previous comment ^

Thanks for raising this issue though!
