### ISSUE TITLE
Replace FallbackComponent with fallback

### ISSUE THREAD

**Issue by alexandernanberg** [bvaughn/react-error-boundary#31]
I think it would be nice if the `<ErrorBoundary>` would have a similar API as `<Suspense>` (fallback instead of FallbackComponent). Don't know if this have been discussed before though.

```js
function App() {
  return <ErrorBoundary fallback={<MyCustomFallback />} />
}
```

I can create a PR if this is something you'd want to add. Can be a non-breaking change if we keep the `FallbackComponent` prop.

**Comment by bvaughn** [comment]
The error boundary feature predates suspense. I'd be fine with that name if this was a new component we were designing, but I don't think it's worth deprecating a property (or adding a redundant secondary property) for. 😄
