### ISSUE TITLE
PNPM - Receiving a react error that prop-types could not be found

### ISSUE THREAD

**Issue by sadsa** [bvaughn/react-error-boundary#33]
When using the PNPM package manager, any dependecies not explicitly mentioned in the `package.json` will be ignored at time of package installation. 

The following code (found in `ErrorBoundaryFallbackComponent.js`) make the following reference to the `prop-types` package.

```
ErrorBoundaryFallbackComponent.propTypes = {
  componentStack: require("prop-types").string.isRequired, <---
  ...
}
```

React apps throw the error `Cannot find module: 'prop-types'. Make sure this package is installed.` because the package was never installed due to no mention of it in the `package.json`

The fix, is to add `prop-types` as a dependency or mark as a peerDependency in the `package.json`.

**Comment by sadsa** [comment]
As mentioned above, if you don't want to include as a hard dependency, you can add it to `peerDependencies` to notify the user we expect that `prop-types` be provided by its dependent (i.e. the consumer)

**Comment by kentcdodds** [comment]
Closing all old issues as we're making significant changes. Please open a new issue if this is still a problem you'd like to have fixed.
