### ISSUE TITLE
As (and recommend) fallback prop

### ISSUE THREAD

**Issue by kentcdodds** [bvaughn/react-error-boundary#34]
Considering this is similar in spirit to Suspense, it would be nice if they share a similar more obvious API.

I really liked this code sample from Joe Savona's talk at react conf:

![IMG_20191025_094055](https://user-images.githubusercontent.com/1500684/67588853-f6deac80-f70b-11e9-938f-563f212cfcf5.jpg)

Thoughts?

**Comment by cbfx** [comment]
i'm with @kentcdodds on this one. i suppose one of us should send a PR...
