### ISSUE TITLE
Don't assume all errors are `Error`

### ISSUE THREAD

**Issue by clehene** [bvaughn/react-error-boundary#36]
Getting this with MobX

```
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `error` of type `String` supplied to `ErrorBoundaryFallbackComponent`, expected instance of `Error`.
    in ErrorBoundaryFallbackComponent (created by ErrorBoundary)
```

Since you can throw any object, an error boundary shouldn't expect only `Error` instances.

**Comment by kentcdodds** [comment]
Closing all old issues as we're making significant changes. Please open a new issue if this is still a problem you'd like to have fixed.

**Comment by tommarien** [comment]
@clehene can you try with version > 3.1.3  ;)
