### ISSUE TITLE
Difference between FallbackComponent, fallbackRender and fallback

### ISSUE THREAD

**Issue by sergiodxa** [bvaughn/react-error-boundary#48]
What is the exact difference between all of those props?

I think `fallback` could receive the `error` and `resetErrorBoundary` function as `fallbackRender`, and the same for `FallbackComponent`, is there a reason to use FallbackComponent` when `fallbackRender` does the same? Or use `fallbackRender` when I could inline the definition of `FallbackComponent` to reset the parent component state?

I'm sure there is a reasoning behind all of those different props but I'm not sure at a first glance 🤔

**Comment by kentcdodds** [comment]
I documented these better just now. Let me know if there's still confusion.

**Comment by Ys-OoO** [comment]
I have the same problem. How can I see your document?
