### ISSUE TITLE
Unnecessary dependencies on package.json when installing

### ISSUE THREAD

**Issue by guilhermebruzzi** [bvaughn/react-error-boundary#5]
Even thought most of these dependencies were on my devDependencies, yarn add it to yarn.lock and node_modules:

```
"dependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.1.1",
    "babel-runtime": "^6.23.0",
    "prop-types": "^15.5.10",
    "webpack": "^3.3.0"
  },
```

I believe most of those dependencies should be a devDependency and prop-types is not a dependency, since you use flow

**Comment by guilhermebruzzi** [comment]
But I just realized that to remove these as a dependency, than you should generate a compiled version (without Flow), right?

**Comment by bvaughn** [comment]
Whoops! I probably just forked another OSS project I had to create this one and wasn't careful about cleaning up dependencies. That or I forgot the `--dev` flag when `yarn add`ing some.

Either way, sorry. I'll tidy up before the next release.

**Comment by bvaughn** [comment]
Should be fixed in 1.1.0!

**Comment by guilhermebruzzi** [comment]
@bvaughn Nice! :D I've copied the component code without Flow (using prop-types instead) to my project, so no extra dependencies were needed, it's small actually:
```js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

class ErrorBoundary extends Component {
  constructor(props, context) {
    super(props, context)

    this.state = {
      error: null,
      info: null,
    }
  }

  componentDidCatch(error, info) {
    const { onError } = this.props

    if (typeof onError === 'function') {
      try {
        onError(error, info ? info.componentStack : '')
      } catch (error) {}
    }

    this.setState({ error, info })
  }

  render() {
    const { children, FallbackComponent } = this.props
    const { error, info } = this.state

    if (error !== null) {
      return (
        <FallbackComponent
          componentStack={info ? info.componentStack : ''}
          error={error}
        />
      )
    }

    return children
  }
}

ErrorBoundary.propTypes = {
  children: PropTypes.any,
  FallbackComponent: PropTypes.any.isRequired,
  onError: PropTypes.func,
}

export default ErrorBoundary
```

**Comment by guilhermebruzzi** [comment]
@bvaughn oh but you should definitely do it anyway, not all people use Flow. Thanks for the great work, this React 16 componentDidCatch feature that this component help to use its very Nice! :D
