### ISSUE TITLE
Types for ErrorBoundary?

### ISSUE THREAD

**Issue by KevinBurton** [bvaughn/react-error-boundary#63]
- `react-error-boundary` version: 2.3.1
- `node` version:14.4
- `npm` version: 6.4.7

Relevant code or config

```javascript
            <ErrorBoundary FallbackComponent={errorFallback}>
            </ErrorBoundary>
```
What you did: Wrapped a section of JSX with the ErrorBoundary component

What happened:

Visual Studio Code complains with a red squiglly line that "no overload matches this call"

Problem description:

I am thinking that the reason that the JSX for ErrorBoundary is causing a warning is that this is inside of a .tsx component and I need type information for the props for ErrorBoundary.

Suggested solution:

Documentation on how to use ErrorBoundary in a TypeScript component.

![image](https://user-images.githubusercontent.com/2643566/89095530-82b8ef80-d394-11ea-8838-77cd57de23fa.png)

**Comment by marcosvega91** [comment]
Hi @KevinBurton thanks for opening this issue :).

Can you share the code of you error component? Can you also please add more info about the error?

**Comment by KevinBurton** [comment]
I just have just Visual Studio Code. I think it is TypeScript lint giving me a warning. There are no runtime errors.

![image](https://user-images.githubusercontent.com/2643566/89107428-a57bf000-d3f6-11ea-8981-37a13773be07.png)

**Comment by kentcdodds** [comment]
What is `errorFallback`? That should be a React component (function or class).

**Comment by KevinBurton** [comment]
I took errorFallback from the examples:

``` JavaScript
const errorFallback = ({error}) => {
    return (
      <div role="alert">
        <p>Something went wrong:</p>
        <pre style={{color: 'red'}}>{error.message}</pre>
      </div>
    )
  }
```

**Comment by marcosvega91** [comment]
If you add type to your props will work

```javascript
const errorFallback = ({ error }: FallbackProps) => {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
      <pre style={{ color: "red" }}>{error?.message}</pre>
    </div>
  );
};
```

**Comment by KevinBurton** [comment]
Thank you. That is what I was looking for.
