### ISSUE TITLE
Update state with getDerivedStateFromError rather than componentDidCatch

### ISSUE THREAD

**Issue by bvaughn** [bvaughn/react-error-boundary#66]
The `componentDidCatch` lifecycle method exists for side effects (e.g. logging). Using `componentDidCatch` to update state and re-render after an error is an anti-pattern and future versions of React will likely skip over error boundaries that don't define `getDerivedStateFromError`.

When ["error boundaries" were first introduced in v16.0](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html), `componentDidCatch` was the only API available. The `static getDerivedStateFromError` API was added in v16.6 to improve the error handling process to avoid the necessity to render an intermediate, broken state before calling the commit-phase `componentDidCatch` hook and *rendering again* to show fallback UI.

I don't use this package for anything so I had forgotten about it being outdated until this morning.

~~Note that this would technically be a breaking change since it would raise the minimum version of React supported from 16.0 to 16.6.~~ Looks like @kentcdodds already raised the "react" dependency to 16.13+ via #46 😅  Guess this wouldn't be a breaking change after all then.

**Comment by kentcdodds** [comment]
Sweet. Thanks for letting me know. I'd welcome a pull request if you'd like, or I can do it later (today probably).

**Comment by bvaughn** [comment]
Not sure if I'll get to it or not. Just wanted to make a note of it while it was on my mind. (Just updated an FB-internal error boundary to fix this same thing.)
