### ISSUE TITLE
Build Error - Declaration or statement expected.  TS1128

### ISSUE THREAD

**Issue by xavierakram** [bvaughn/react-error-boundary#77]
Hi, I've ran into bugs whilst trying to create a production build of my application the error seems to be related with `TS1128` Declaration or Statement Expected.

```
Creating an optimized production build...
Failed to compile.

/home/runner/work/.../node_modules/react-error-boundary/dist/index.d.ts
TypeScript error in /home/runner/work/.../node_modules/react-error-boundary/dist/index.d.ts(53,1):
Declaration or statement expected.  TS1128

    51 | declare function useErrorHandler<P = Error>(givenError?: P | null | undefined): React.Dispatch<React.SetStateAction<P | null>>;
    52 | export { ErrorBoundary, withErrorBoundary, useErrorHandler };
  > 53 | export type { FallbackProps, ErrorBoundaryPropsWithComponent, ErrorBoundaryPropsWithRender, ErrorBoundaryPropsWithFallback, ErrorBoundaryProps, };
       | ^
    54 |


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ... build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ... build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-12-02T17_39_28_869Z-debug.log
Error: Process completed with exit code 1.
```

"react-error-boundary": "^3.1.0",

This is executing via GitHub actions to app-engine, so I'd assume it's using the latest version of NPM / Node.

**Comment by kentcdodds** [comment]
Sorry @xavierakram, but I'm not sure what that could be. TypeScript *generated* that file, so there must be some weird config issue with your version of TypeScript *reading* a file that TypeScript *generated* 🤷‍♂️

**Comment by xavierakram** [comment]
@kentcdodds thanks for responding, I've got the following tsconfig file which seems to be rather standard, but I only seem to get an error with React-Error-Boundary.

`{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "./src",
    "esModuleInterop": true,
    "lib": ["dom", "es2015"],
    "jsx": "react",
    "target": "es5",
    "allowJs": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "include": ["src"]
}`

any insight would be grateful.

**Comment by xavierakram** [comment]
For anyone else experiencing the same issue I realised that[ type-only imports and exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-exports) were introduced in Typescript 3.8, upgrading typescript on the project resolved this issue.

**Comment by ddennis** [comment]
@xavierakram had the same error with typescript 3.7.1 - updated typescript to 4.1.2 and everything worked
