### ISSUE TITLE
typescript error : Parameter 'props' implicitly has an 'any' type. 

### ISSUE THREAD

**Issue by eran-or** [bvaughn/react-error-boundary#82]
src/base/error-boundary/ErrorBoundary.tsx(4,15):
Parameter 'props' implicitly has an 'any' type.  TS7006

    2 | 
    3 | class ErrorBoundary extends React.Component {
  > 4 |   constructor(props) {
      |               ^
    5 |     super(props);
    6 |     this.state = { hasError: false };
    7 |   }

this is my code const container = document.getElementById('root')

function ErrorFallback({error, resetErrorBoundary}: FallbackProps) {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
      <pre>{error.message}</pre>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  )
}

ReactDOM.render(
  <React.StrictMode>
      <ErrorBoundary 
      FallbackComponent={ErrorFallback}
      onReset={() =>console.log("on Reset error boundaries")}
      // resetKeys={[false]}
    >
    <Router />
    </ErrorBoundary>
  </React.StrictMode>,
  container
);

help... is this is a bug or user issue :( 
If it is my mistake then how to use it right?

**Comment by tommarien** [comment]
@eran-or can you give a code sandbox demonstrating the issue ?
