### ISSUE TITLE
No only Error for FallbackProps

### ISSUE THREAD

**Issue by viclafouch** [bvaughn/react-error-boundary#83]
I'm using React-query, and we can type our error. But there is a conflit with react-error-boundary since the type is not an Error type, but a custom. How can we deal with that ?

![image](https://user-images.githubusercontent.com/23353836/107959820-28842280-6fa4-11eb-9fd4-b1bc8978ba2a.png)

- `react-error-boundary` version: 3.1.0
- `node` version: 12.19.1
- `npm` version: 6.14.10

Relevant code or config

```js
const OrderDetailsViews = (
  props: RouteComponentProps<TParams>
): React.ReactElement => {
  const { match } = props
  const { t } = useTranslation()
  const orderId = Number(match.params.id)
  const handleError = useErrorHandler()

  const { data: order, error, refetch: refetchOrders } = useQuery<
    FindOneOrder,
    ApiError
  >(['order-details', orderId], () => api.orders.findOneComplete(orderId), {
    onError: err => handleError(err) <-- ERROR TYPE
  })
}
```

Suggested solution: We can pass our type like : `handleError<ApiError>(err)`

OR

```ts
interface FallbackProps<T extends Error> { <-- We can pass something else
    error: T;
    resetErrorBoundary: (...args: Array<unknown>) => void;
}
```

**Comment by kentcdodds** [comment]
That suggested solution sounds fine to me 👍

**Comment by tommarien** [comment]
What is the need for it to be an error ? and not `unknown` like in node?

```
try {} catch(e: unknown){}
```

**Comment by tommarien** [comment]
Is it ok if i try to change the error type to unknown in a pull request, in the next coming days? Something in the order of this

```ts
import React, { useCallback } from "react";

function useErrorHandler(givenError?: unknown): (error: unknown) => void {
  const [error, setError] = React.useState<unknown>(givenError ?? null);
  if (error !== null) throw error;

  const onError = useCallback(
    (err: unknown) => {
      setError(err ?? null);
    },
    [setError]
  );

  return onError;
}

```
Would you guys accept a pull containing this change ?

**Comment by kentcdodds** [comment]
I'm not sure why the `useCallback` is necessary... And this would break the `useErrorHandler(error)` API. Why couldn't the change just be:

```tsx
function useErrorHandler(
  givenError?: unknown,
): React.Dispatch<React.SetStateAction<unknown>> {
  const [error, setError] = React.useState<unknown | null>(null)
  if (givenError) throw givenError
  if (error) throw error
  return setError
}
```

**Comment by kentcdodds** [comment]
In fact, I think it could be further simplified to this:

```tsx
function useErrorHandler(givenError?: unknown) {
  const [error, setError] = React.useState<unknown>(null)
  if (givenError) throw givenError
  if (error) throw error
  return setError
}
```

The return type can be inferred without any trouble.

**Comment by tommarien** [comment]
Should try to explain why i did things ;)

1. Explicit return type, as it is a boundary method i included this change (which could be seen as a contract breach, but the end result is the same only closed
```ts
// inferred type
React.Dispatch<React.SetStateAction<unknown>>

// preferred type
(error:unknown) => void
```

2. Removed duplication between given error and state error, moved the givenerror (i presumed its something like initialError)

```ts
function useErrorHandler(givenError?: unknown) {
  const [error, setError] = React.useState<unknown>(null)
  if (givenError) throw givenError
  if (error) throw error
}
```
ends up in:
```ts
function useErrorHandler(givenError?: unknown) {
  const [error, setError] = React.useState<unknown>(givenError)
  if (error) throw error
}
```

3. The callback/ `?? null` shenanigan
In javascript you could technically throw all falsy values like `null, undefined,` but also `0, false and ''`, consider following scenario

```ts
const onError = useErrorHandler();

useEffect(()=>{
  function async fetchy() {
    promise.catch(onError);
  }
  fetchy();
}, [onError])

```
In the change i made i ensure everything except undefined and null would be rethrown

Sorry should have given explaination in the first place. For me the minimum change you did is also fine but just wanted to give my angle on it ;)

**Comment by kentcdodds** [comment]
> 1. Explicit return type

I guess that's ok

> 2. Removed duplication

That's not duplication. The suggested change would actually change the behavior. The `givenError` could be changed by the calling code and we want to capture that.

> 3. The callback/ `?? null` shenanigan

I guess that makes sense too.

With that, here's a good implementation:

```tsx
function useErrorHandler(givenError?: unknown): (error: unknown) => void {
  const [error, setError] = React.useState<unknown>(null)
  if (givenError != null) throw givenError
  if (error != null) throw error
  return setError
}
```

**Comment by kentcdodds** [comment]
And I would consider this a bug fix

**Comment by tommarien** [comment]
@kentcdodds thanks for the assist and discussion ;)
