### ISSUE TITLE
Dependency on @babel/runtime

### ISSUE THREAD

**Issue by thdk** [bvaughn/react-error-boundary#87]
Small question, why does `react-error-boundary` has a dependency on ´@babel/runtime`?

**Comment by kentcdodds** [comment]
Hi @thdk,

You can see what is used in the built output: https://unpkg.com/browse/react-error-boundary@3.1.1/dist/react-error-boundary.esm.js

Pretty much every practical react application will use babel runtime through dependencies at least because it's a good way to share the common dependencies.
