### ISSUE TITLE
Show some Fallback component

### ISSUE THREAD

**Issue by tgmarinho** [bvaughn/react-error-boundary#88]
Hi, thanks for this lib ;)

Is there a way to show the fallback component replacing the component that throws the error?

I don't want to put `<ErrorBoundary><Products /> <ErrorBoundary>, <ErrorBoundary><People /> <ErrorBoundary>, <ErrorBoundary><User /> <ErrorBoundary> ` inside of each component that expects data from API.

I just want to put <ErrorBoundary><App /> <ErrorBoundary>  and then it will show some component fallback when crashing the Products component.

**Comment by kentcdodds** [comment]
Hi @tgmarinho, I don't think that's possible, and even if it were, I think it'd better to be more explicit anyway.
