### ISSUE TITLE
Not Working with Childrens

### ISSUE THREAD

**Issue by LuisValgoi** [bvaughn/react-error-boundary#91]
I may be using it wrong, but here it goes.

- `react-error-boundary` version: ^3.1.3
- `node` version: v14.17.0
- `npm` version: 7.14.0

Relevant code or config

![image](https://user-images.githubusercontent.com/8363610/119904185-515f7080-bf20-11eb-9232-f2afd73b9642.png)

What you did:

- Created a `<Page />`.
- Inside this `<Page />`, wrapped its `childrens` with `react-error-boundary`.
- Created a `<Home />` which uses this `<Page />` with a button which once clicked `throw new Error()`.

What happened:

- Once clicked into this button, the error popups but the `FallbackComponent` (`Error`) is not shown

**Comment by Maximilianos** [comment]
Hey @LuisValgoi, I am not one of the maintainers - but just thought I'd chime in. 

I might be wrong, but one issue I can see with the code you provided is that you are throwing the error **inside a click event handler**. [This is not catchable automatically by react error boundaries unfortunately](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries). To handle such a case you should use the [`useErrorBoundary`](https://github.com/bvaughn/react-error-boundary#useerrorhandlererror-unknown) hook that `react-error-boundary` provides, i.e. something like the following:
```javascript
...
import { useErrorBoundary } from 'react-error-boundary';

const Home = () => {
  ...
  const handleError = useErrorBoundary();
  return (
    <Page ...>
      <button onClick={() => {
        try {
          throw new Error("cre"); // replace this line with the something that might throw in the real implementation
        } catch (error)
          handleError(error);
        }
      }>
        {isLoading ? ... }
      </button>
    </Page>
  );
};
```
You can also simulate an error directly in the component render path, [like this example too](https://github.com/bvaughn/react-error-boundary#error-recovery), (this doesn't need any extra hooks from react-error-boundary) if you want to see if that works too:
```javascript
...
const ThrowsError = () => { // replace this component with the component that might throw in the real implementation
  throw new Error("cre");
};
const Home = () => {
  ...
  const [shouldThrow, setShouldThrow] = useState(false);
  return (
    <Page ...>
      <button onClick={() => setShouldThrow(true)}>
        {shouldThrow ? <ThrowsError /> : 'not cre'}
      </button>
    </Page>
  );
};
```
One that I am not sure will work, haven't tested (feel free to test yourself) is:
```javascript
...
const cre = () => { // note this is **not** a component - just a normal function
  throw new Error("cre"); 
}; 
const Home () => {
  ...
  const [shouldThrow, setShouldThrow] = useState(false);
  return (
    <Page ...>
      <button onClick={() => setShouldThrow(true)}>
        {shouldThrow ? cre() : 'not cre'}
      </button>
    </Page>
  );
};
```
Try these out, let me know if they work. Hope that was helpful.

**Comment by dedoyle** [comment]
ErrorBoundry not work even if I have used useErrorHandler.

[code sandbox](https://codesandbox.io/s/react-error-handler-gzvkv?file=/src/App.js)

```js
import React from "react";
import { ErrorBoundary, useErrorHandler } from "react-error-boundary";
import "./styles.css";

function ErrorFallback({ error, resetErrorBoundary }) {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
      <pre>{error.message}</pre>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  );
}

function Bomb() {
  const handleError = useErrorHandler();
  // throw new Error('💥 CABOOM 💥')
  try {
    throw new Error("💥 CABOOM 💥");
  } catch (error) {
    console.log(error);
    handleError(error);
  }
}

export default function App() {
  const [explode, setExplode] = React.useState(false);

  return (
    <div>
      <button onClick={() => setExplode((e) => !e)}>toggle explode</button>
      <ErrorBoundary
        FallbackComponent={ErrorFallback}
        onReset={() => setExplode(false)}
        resetKeys={[explode]}
      >
        {explode ? <Bomb /> : null}
      </ErrorBoundary>
    </div>
  );
}
```

**Comment by Xxxdxs** [comment]
> ErrorBoundry not work even if I have used useErrorHandler.
> 
> [code sandbox](https://codesandbox.io/s/react-error-handler-gzvkv?file=/src/App.js)
> 
> ```js
> import React from "react";
> import { ErrorBoundary, useErrorHandler } from "react-error-boundary";
> import "./styles.css";
> 
> function ErrorFallback({ error, resetErrorBoundary }) {
>   return (
>     <div role="alert">
>       <p>Something went wrong:</p>
>       <pre>{error.message}</pre>
>       <button onClick={resetErrorBoundary}>Try again</button>
>     </div>
>   );
> }
> 
> function Bomb() {
>   const handleError = useErrorHandler();
>   // throw new Error('💥 CABOOM 💥')
>   try {
>     throw new Error("💥 CABOOM 💥");
>   } catch (error) {
>     console.log(error);
>     handleError(error);
>   }
> }
> 
> export default function App() {
>   const [explode, setExplode] = React.useState(false);
> 
>   return (
>     <div>
>       <button onClick={() => setExplode((e) => !e)}>toggle explode</button>
>       <ErrorBoundary
>         FallbackComponent={ErrorFallback}
>         onReset={() => setExplode(false)}
>         resetKeys={[explode]}
>       >
>         {explode ? <Bomb /> : null}
>       </ErrorBoundary>
>     </div>
>   );
> }
> ```



> ErrorBoundry not work even if I have used useErrorHandler.
> 
> [code sandbox](https://codesandbox.io/s/react-error-handler-gzvkv?file=/src/App.js)
> 
> ```js
> import React from "react";
> import { ErrorBoundary, useErrorHandler } from "react-error-boundary";
> import "./styles.css";
> 
> function ErrorFallback({ error, resetErrorBoundary }) {
>   return (
>     <div role="alert">
>       <p>Something went wrong:</p>
>       <pre>{error.message}</pre>
>       <button onClick={resetErrorBoundary}>Try again</button>
>     </div>
>   );
> }
> 
> function Bomb() {
>   const handleError = useErrorHandler();
>   // throw new Error('💥 CABOOM 💥')
>   try {
>     throw new Error("💥 CABOOM 💥");
>   } catch (error) {
>     console.log(error);
>     handleError(error);
>   }
> }
> 
> export default function App() {
>   const [explode, setExplode] = React.useState(false);
> 
>   return (
>     <div>
>       <button onClick={() => setExplode((e) => !e)}>toggle explode</button>
>       <ErrorBoundary
>         FallbackComponent={ErrorFallback}
>         onReset={() => setExplode(false)}
>         resetKeys={[explode]}
>       >
>         {explode ? <Bomb /> : null}
>       </ErrorBoundary>
>     </div>
>   );
> }
> ```

It doesn't work in development environment, in fact, it works. you can close the error overlay in the right corner.

**Comment by YouWillBe** [comment]
I also confirmed that it is not working
![image](https://user-images.githubusercontent.com/16474244/143540845-cde199e8-1ff0-4525-b3a8-4c578df10221.png)

**Comment by bvaughn** [comment]
This is the correct answer:
https://github.com/bvaughn/react-error-boundary/issues/91#issuecomment-858975575
