### ISSUE TITLE
Keep rendering children on error

### ISSUE THREAD

**Issue by jhonabreul** [bvaughn/react-error-boundary#94]
As always, thank you for this module!

I was wondering if there is a way to catch errors but keep rendering the childrens. For instance, I would like to catch errors and show a toast alert over the content, but keeping it instead of replacing it with the fallback component. Is this possible?

Thanks!

**Comment by kentcdodds** [comment]
Hi @jhonabreul,

This may be possible (if you can somehow keep track of the DOM and replace the children DOM with the previous version of the DOM that worked), but this would be riddled with bugs I'm sure and pretty hacky.

Sorry, I don't think this would be practical.
