### ISSUE TITLE
Update docs to explicitly mention that react error overlay renders in dev mode

### ISSUE THREAD

**Issue by Jakkc** [bvaughn/react-error-boundary#99]
Hey,

Would be really helpful if you could update the docs to explicitly state that when in dev mode React ends up rendering the error overlay screen. Very confusing and ended up tripping me up for a good hour before I read the final paragraph of [this article](https://kentcdodds.com/blog/use-react-error-boundary-to-handle-errors-in-react)

Thanks!

**Comment by kentcdodds** [comment]
That has nothing to do with react-error-boundary or React. That's a feature of Create React App. Feel free to make a PR to add a note about it in the README if you'd like though.
